### ISSUE TITLE
[EKS] [request]: CoreDNS does not have pod disruption budget

### ISSUE THREAD

**Issue by aaronmell** [aws/containers-roadmap#1028]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
CoreDNS does not set a PDB, this can cause both instances to go down during a rolling restart, or if the node is scheduled for termination. 

**Which service(s) is this request for?**
This could be EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
We patch nodes on a weekly basis. We do a rolling restart on nodes as we patch them. Because of this, all coredns instances go down during the recycle. 

**Are you currently working around this issue?**
We just discovered it. Most likely we will add a step to apply a PDB manually for coredns to prevent both from being down at once

**Comment by benwaffle** [comment]
Here's the yaml I used. My cluster had coredns auto-installed via `eksctl`.

```yaml
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: coredns
  namespace: kube-system
spec:
  minAvailable: 1
  selector:
    matchLabels:
      k8s-app: kube-dns
```

**Comment by yann-soubeyrand** [comment]
If you happen to have your two CoreDNS pods on the same node (it could be great to have topology spread constraint), launching a managed node group update will evict the two pods at the same time, leading to a service outage. A PDB seems pretty necessary.

**Comment by mamoit** [comment]
This is one of those problems that I didn't want to run into the hard way.
A simple PDB that can assure that at least one is available at all times is essential for `coredns`.

**Comment by matti** [comment]
yesterday had a massive outage because of this.

**Comment by iramello** [comment]
nice to see progress on this, quick resolution, thanks aws !

**Comment by mamoit** [comment]
We had our own sideloaded PDB because of this, where we set `minAvailable`.
Today we upgraded the addon on a test cluster and terraform gave us a nice
`│ 	* : UnsupportedAddonModification: PodDisruptionBudget.policy "coredns" is invalid: spec: Invalid value: policy.PodDisruptionBudgetSpec{MinAvailable:(*intstr.IntOrString)(0xc0207f1160), Selector:(*v1.LabelSelector)(0xc0207f1180), MaxUnavailable:(*intstr.IntOrString)(0xc0207f11a0), UnhealthyPodEvictionPolicy:(*policy.UnhealthyPodEvictionPolicyType)(nil)}: minAvailable and maxUnavailable cannot be both set`

So I guess the addon is now setting `maxUnavailable`?
I'll check tomorrow for sanity's sake.

**Comment by mamoit** [comment]
Ok, just reinstalled the addon and now in `v1.10.1-eksbuild.2` there is indeed a pdb managed by the coredns addon
``` yaml
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  labels:
    eks.amazonaws.com/component: coredns
    k8s-app: kube-dns
  name: coredns
  namespace: kube-system
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      eks.amazonaws.com/component: coredns
      k8s-app: kube-dns
```
