### ISSUE TITLE
[EKS]: Support for Kubernetes 1.19

### ISSUE THREAD

**Issue by dominik-lekse** [aws/containers-roadmap#1053]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
Support Kubernetes 1.19

**Which service(s) is this request for?**
EKS

**Comment by mikestef9** [comment]
EKS support for Kubernetes version 1.19 is now available. We recommend thoroughly looking through 1.19 release notes in the linked doc page below, as there are some important callouts.

- [What's New](https://aws.amazon.com/about-aws/whats-new/2021/02/amazon-eks-supports-kubernetes-version-1-19/)
- [EKS Docs](https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html#kubernetes-1.19)

**Comment by marcincuber** [comment]
I think it is worth noting that when you update your `kube-proxy` to version 1.19.6. You will see errors related to `endpointslices`. Remember to update your clusterrole. Mine looks as follows:

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: system:node-proxier
rules:
- apiGroups:
  - ""
  resources:
  - endpoints
  - services
  verbs:
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
  - update
- apiGroups:
  - "discovery.k8s.io"
  resources:
  - endpointslices
  verbs:
  - watch
  - list
  - get
```
