### ISSUE TITLE
[EKS][Fargate] [request]: Support SYS_PTRACE for EKS Fargate 

### ISSUE THREAD

**Issue by evq** [aws/containers-roadmap#1102]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
What do you want us to build?

Support SYS_PTRACE for EKS Fargate ( already supported on ECS )

**Which service(s) is this request for?**
Fargate on EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Debugability and introspection of running workloads. May also allow for an alternative method for capturing process stdout to allow [sidecar logging with EKS Fargate](https://aws.amazon.com/blogs/containers/how-to-capture-application-logs-when-using-amazon-eks-on-aws-fargate/) in a more transparent method through stdout redirection.

See https://github.com/aws/containers-roadmap/issues/409 for the same request on ECS.

**Are you currently working around this issue?**

**Additional context**

**Attachments**

**Comment by j-rat** [comment]
We are looking to have this capability to perform run time analysis of workloads.

**Comment by d0nwilliams** [comment]
I too echo this We are looking to have this capability to perform run time analysis of workloads.

**Comment by ollypom** [comment]
EKS Fargate doesn't explicity support ptrace workloads today, however it does not prevent you from running them either. This is because no seccomp policy is applied to Kubernetes Pods by default. This will change in the future (Maybe [Kubernetes 1.25](https://github.com/kubernetes/enhancements/issues/2413)), and when it does you could write a custom seccomp policy to allow a pod to use ptrace. That being said EKS/Fargate should allow you to add the ptrace capability explicity (as it does on ECS/Fargate), so this issue should stay open. In the mean time, for those curious, you can run ptrace workloads on EKS/Fargate today.

---

### A quick test using strace:

Dockerfile

```
FROM debian

RUN apt-get update && \
    apt-get install strace -y

CMD ["strace", "echo", "hello"]
```

Deploy 3 Pods to EKS Fargate:

1. A "default pod" with no seccomp policy.

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: defaultpod
spec:
  restartPolicy: Never
  containers:
  - name: strace
    image: 111222333444.dkr.ecr.eu-west-1.amazonaws.com/strace:latest
```

2. A "seccomp pod", this is a Pod with the runtime seccomp policy applied

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: seccomppod
spec:
  restartPolicy: Never
  securityContext:
    seccompProfile:
      type: RuntimeDefault
  containers:
  - name: strace
    image: 111222333444.dkr.ecr.eu-west-1.amazonaws.com/strace:latest
```

3. A "ptrace pod", this is a Pod with the runtime seccomp policy applied, but I am attempting to explicitly add ptrace to my Pod.

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: ptracepod
spec:
  restartPolicy: Never
  securityContext:
    seccompProfile:
      type: RuntimeDefault
  containers:
  - name: strace
    image: 111222333444.dkr.ecr.eu-west-1.amazonaws.com/strace:latest
    securityContext:
      capabilities:
        add: ["SYS_PTRACE"]
```

### The Results:

```bash
$ kubectl get pods
NAME          READY   STATUS      RESTARTS   AGE
defaultpod    0/1     Completed   0          7m30s
seccomppod    0/1     Error       0          7m30s
ptracepod     0/1     Pending     0          7m30s
```

1. The default pod worked.

```bash
$ kubectl logs defaultpod
execve("/bin/echo", ["echo", "hello"], 0x7ffd1acc9888 /* 18 vars */) = 0
brk(NULL)                               = 0x559437d47000
access("/etc/ld.so.preload", R_OK)      = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=6562, ...}) = 0
mmap(NULL, 6562, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7ff492ad7000
close(3)
```

2. The seccomp pod ran but strace got blocked by the runtime seccomp policy.

```bash
$ kubectl logs -f seccomppod
strace: test_ptrace_get_syscall_info: PTRACE_TRACEME: Operation not permitted
strace: ptrace(PTRACE_TRACEME, ...): Operation not permitted
strace: PTRACE_SETOPTIONS: Operation not permitted
strace: detach: waitpid(9): No child processes
strace: Process 9 detached
```

3. The ptrace pod got blocked by the scheduler as EKS Fargate does not allow the ptrace Linux capability.

```bash
$ kubectl describe pod ptracepod
<snip>
Events:
  Type     Reason            Age    From               Message
  ----     ------            ----   ----               -------
  Warning  FailedScheduling  9m42s  fargate-scheduler  Pod not supported on Fargate: invalid SecurityContext fields: Capabilities added: SYS_PTRACE
```
