### ISSUE TITLE
[FARGATE/EKS] [request]: support topology.kubernetes.io/zone for nodeSelector/nodeAffinity rule

### ISSUE THREAD

**Issue by tsahiduek** [aws/containers-roadmap#1125]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
What do you want us to build?
 Support new "well-known label" of `topology.kubernetes.io/zone` which deprecates the old one of `failure-domain.beta.kubernetes.io/zone` (see https://kubernetes.io/docs/reference/kubernetes-api/labels-annotations-taints/#failure-domainbetakubernetesiozone)

**Which service(s) is this request for?**
Fargate EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**

EKS Fargate support scheduling pods to a specific AZ by using nodeSelector or nodeAffinity with the well known label of `failure-domain.beta.kubernetes.io/zone`.
The above label is deprecated in 1.17 in favor of `topology.kubernetes.io/zone`.
When trying to schedule pod to a specific AZ using the new label of `topology.kubernetes.io/zone`, an event with a message of `MatchNodeSelector failed: Fargate profile fp-default cannot satisfy pod's node selector/affinity requirement` is set on the 
pod itself (via a describe command)

This is handful when user wants to run a pod in a specific AZ

**Are you currently working around this issue?**
Using the old `failure-domain.beta.kubernetes.io/zone` label for nodeAffinity/NodeSelector

**Additional context**

**Attachments**
Deployment example:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fargate
spec:
  selector:
    matchLabels:
      app: fargate
  replicas: 1
  template:
    metadata:
      labels:
        fargate: enable # this used for the Fargate profile selector
        app: fargate
    spec:
      nodeSelector:
        # topology.kubernetes.io/zone: eu-west-1b
        failure-domain.beta.kubernetes.io/zone: eu-west-1b
      containers:
        - name: fargate
          image: "nginx"
```
