### ISSUE TITLE
[EKS]: Support AWS Load Balancer Controller in EKS add-ons

### ISSUE THREAD

**Issue by leandrocostam** [aws/containers-roadmap#1162]
Add support for managing AWS Load Balancer Controller with EKS add-ons.

**Comment by gregoryfranklin** [comment]
The Load Balancer Controller seems like something that should be on the controlplane rather than an add-on.  Same goes for the CSI driver.

**Comment by ckdarby** [comment]
Here is an example of an issue we have where we find ourselves falling short between AWS & EKS with load balancers.

I would like to take advantage of VPC endpoint service to allow another AWS account to use private endpoint to talk to something running within kubernetes and not over public network.

Would look something like this:
AWS Account A [Lambda -> Private endpoint] -> Account B [ VPC endpoint service -> Internal NLB -> Kubernetes -> Service]

The problem here is kind of a chicken & egg situation that requires cluster post installs. We're not able to set up the VPC endpoint service until the NLB exists but the NLB won't exist until kubectl apply (helm install in our case) happens on the application side because that has the load balancer resource.

Our "hack around this:
 - terraform for initial infrastructure (vpc, eks, etc)
 - helm install (applications)
 - terraform post install (vpc endpoint service now that the NLB exists from the application)

**Comment by jwenz723** [comment]
Will the aws-load-balancer-controller EKS Add-On support customizations?

I currently use the helm chart in the eks-charts repo to install this controller. Here are the helm values that we specify:

```yaml
replicaCount: 1
podAnnotations:
    nice.com/owner: owner@email.com
    nice.com/product: aws-load-balancer-controller
serviceAnnotations:
    nice.com/owner: owner@email.com
    nice.com/product: aws-load-balancer-controller
clusterName: {{ .Values.global.eksClusterName }}
serviceAccount:
    annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::123456789012:role/role-for-aws-load-balancer-controller
    nice.com/owner: owner@email.com
    nice.com/product: aws-load-balancer-controller
    create: true
    name: aws-load-balancer-controller
rbac:
    create: true
podSecurityContext:
    fsGroup: 65534
securityContext:
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    allowPrivilegeEscalation: false
terminationGracePeriodSeconds: 10
resources:
    limits:
    cpu: 200m
    memory: 128Mi
    requests:
    cpu: 100m
    memory: 50Mi
ingressClass: alb
enableShield: true
enableWaf: true
enableWafv2: true
logLevel: info
```
