### ISSUE TITLE
[service] [request]: describe request here

### ISSUE THREAD

**Issue by dza89** [aws/containers-roadmap#1212]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
Add pod disruption budget by default for coredns

**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Zero downtime for coredns during nodeswap

**Are you currently working around this issue?**
How are you currently solving this problem?
Adding it manually

```yaml
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: coredns
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      eks.amazonaws.com/component: coredns
```

**Additional context**
-

**Attachments**
-
