### ISSUE TITLE
[EKS] [issue]: Failed to watch *v1.Node: failed to list *v1.Node: Unauthorized"

### ISSUE THREAD

**Issue by Ph4rell** [aws/containers-roadmap#1228]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
What do you want us to build?

**Which service(s) is this request for?**
This could be EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Trying to get informations about EKS nodes from an ECS prometheus via an API call to the HTTPS endpoint.

**Are you currently working around this issue?**
How are you currently solving this problem?

**Additional context**
Anything else we should know?
ECS logs : `level=error ts=2021-01-18T13:50:37.349Z caller=klog.go:96 component=k8s_client_runtime func=ErrorDepth msg="/app/discovery/kubernetes/kubernetes.go:515: Failed to watch *v1.Node: failed to list *v1.Node: Unauthorized"`

Prometheus configuration:
```
- job_name: 'eks-nodes'
    scheme: https
    tls_config:
        ca_file: /etc/prometheus/ca.crt
    bearer_token_file: /etc/prometheus/token
    kubernetes_sd_configs:
    - role: node
      api_server: "https://xxxxxxxxxx.eks.amazonaws.com"
      tls_config:
        ca_file: /etc/prometheus/ca.crt
      bearer_token_file: /etc/prometheus/token
    relabel_configs:
    - action: labelmap
      regex: __meta_kubernetes_node_label_(.+)
```
