### ISSUE TITLE
[EKS] [request]: Spot & On-demand Mixed Policy for Managed Node Group

### ISSUE THREAD

**Issue by yyhpys** [aws/containers-roadmap#1297]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
Spot & On-demand Mixed Policy for Managed Node Group

**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Currently our team is using the node group with following options.

onDemandBaseCapacity
onDemandPercentageAboveBaseCapacity

Those options give us some stability in our cluster while using spot instances to reduce the cost.

We hope to migrate our EKS cluster to utilize managed node group, but reluctant to fully moving our node-group to spot-only group. So if such options are given to Managed node group's spot type it will be grateful.

**Are you currently working around this issue?**
We are currently using basic node group to use mixed policy.

**Additional context**
-

**Attachments**
-

**Comment by drewhemm** [comment]
I am currently using a workaround for this issue. I create the Managed Node Groups (MNGs) with Terraform, and then use a `null_resource` to set the on-demand base capacity:

```terraform
# This resource sets the on-demand base capacity for the node group
resource "null_resource" "set_on_demand_base_capacity" {
  count = can(var.config.on_demand_base) ? 1 : 0

  triggers = {
    autoscaling_group_name = aws_eks_node_group.this.resources[0].autoscaling_groups[0].name
    on_demand_base         = var.config.on_demand_base
  }

  provisioner "local-exec" {
    command = <<EOT
      aws autoscaling update-auto-scaling-group \
        --auto-scaling-group-name ${aws_eks_node_group.this.resources[0].autoscaling_groups[0].name} \
        --mixed-instances-policy '{"InstancesDistribution": {"OnDemandBaseCapacity": ${var.config.on_demand_base}}}'
    EOT
  }
}
```

This works fine, but the problem is that the on-demand EC2 instances that are created have the wrong value for their capacityType label.

```yaml
metadata:
  annotations:
    alpha.kubernetes.io/provided-node-ip: 10.0.3.98
  labels:
    eks.amazonaws.com/capacityType: SPOT
```

![Image](https://github.com/user-attachments/assets/40d4c240-d6fb-4987-b8f1-3a312c6815c7)

As you can see from the EC2 screenshot, the instance lifecycle is `normal`, therefore the value of the label should be `ON_DEMAND`. 

I have discussed this with AWS Support and they say it is because the node labelling is based purely on the MNG data in EKS, and does not take into the account the data about the instance from EC2. The recommendation is to instead create two separate MNGs, one spot and one on-demand. I would prefer to use a single ASG, as Cluster Autoscaler (or the ASG itself) will ensure a better AZ-spread. 

I thought of another workaround, which would be to run a workload that queries the EC2 API and label the nodes accordingly, similar to https://github.com/enver/label-nodes

**Comment by drewhemm** [comment]
In answer to [this question](https://github.com/aws/containers-roadmap/issues/1561#issuecomment-973016104), this should be how to target nodes based on their capacityType in a mixed MNG/ASG, and also how to spread workloads:

```yaml
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          preference:
            matchExpressions:
              - key: eks.amazonaws.com/capacityType
                operator: In
                values:
                  - SPOT
  topologySpreadConstraints:
    - maxSkew: 1
      minDomains: 2
      topologyKey: eks.amazonaws.com/capacityType
      whenUnsatisfiable: DoNotSchedule
      labelSelector:
        matchLabels:
          app.kubernetes.io/name: '{{ include "ingress-nginx.name" . }}'
          app.kubernetes.io/instance: '{{ .Release.Name }}'
          app.kubernetes.io/component: controller
      matchLabelKeys:
        - pod-template-hash
```
