### ISSUE TITLE
[ECS] [request]: EC2 Capacity Provider - drain instances on AMI replacements

### ISSUE THREAD

**Issue by elruwen** [aws/containers-roadmap#1365]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
I got a simple web application behind an ALB. I run my containers on ECS backed by EC2. I deploy all this via cloudformation. My Autoscaling Group has the following update policy:
```
    UpdatePolicy:
      AutoScalingRollingUpdate:
        MinInstancesInService: 1
        MaxBatchSize: 1
        WaitOnResourceSignals: false
        PauseTime: "PT3M00S"
        SuspendProcesses:
          - "ScheduledActions"
```

**Which service(s) is this request for?**
ECS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
I am managing my system via cloudformation. Every now and then I want to deploy a new AMI (security patches etc). When I am doing that, Cloudformation replaces one by one the EC2 instances. But there is no communication with ECS or the ALB, so the instances are not drained and the ALB still tries to serve requests from EC2 which are already gone and customers get a 502 or a 503.
I can fix that with a lambda which intercepts the instance termination process and manually drains the EC2 instance. But every AWS customer who uses the EC2 capacity provider and serves traffic via a load balancer needs the same lambda. Imho it should be part of the EC2 Capacity Provider.

**Are you currently working around this issue?**
I can use a Lambda as an Autoscaling Lifecycle hook to intercept the shutting down of the EC2 instance and drain the instance manually. See https://github.com/aws-samples/ecs-cid-sample

**Additional context**

**Attachments**
If required I can provide an example cloudformation stack.
