### ISSUE TITLE
[ECS] [request]: extend ECS Deployment State Change Event

### ISSUE THREAD

**Issue by dmnlk** [aws/containers-roadmap#1371]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
What do you want us to build?

ECS Deployment State has little information.
Please add more information (ex: Cluster name and Service name) to event .

**Which service(s) is this request for?**
ECS
EventBridge
Chatbot

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
What outcome are you trying to achieve, ultimately, and why is it hard/impossible to do right now? What is the impact of not having this problem solved? The more details you can provide, the better we'll be able to understand and solve the problem.

I'm integrating ECS+EventBridge+Chatbot for notify deployment event to Slack.
But, this notification has litter information.

like this.

---
:mega: ECS Deployment State Change | ap-northeast-1 | Account: XXXXX
ECS deployment ecs-svc/3172XXXXXX in progress.
Deployment ID  ecs-svc/3172XXXXXX
Event type  INFO
Event name  SERVICE_DEPLOYMENT_IN_PROGRESS
Updated at  Thu, 13 May 2021 08:30:17 GMT
---

This information does not tell you which services in which cluster are deployed. 

Please extend the event metadata.
https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs_cwe_events.html

**Are you currently working around this issue?**
How are you currently solving this problem?
no.

**Comment by lionello** [comment]
In particular, we cannot make an EventBridge rule to filter on the `clusterArn` like we can for "ECS Task State Change" and "ECS Service Action".

**Comment by msmyth-influencer** [comment]
Any update on if this will be included? As both the "ECS Service Action" or "ECS Task State Change" does not satisfy what we need and all we require is the deployment status with clustername/service etc.

**Comment by lvthillo** [comment]
It seems [the event](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs_service_deployment_events.html) contains the resources now.

```
{
   "version": "0",
   "id": "ddca6449-b258-46c0-8653-e0e3aEXAMPLE",
   "detail-type": "ECS Deployment State Change",
   "source": "aws.ecs",
   "account": "111122223333",
   "time": "2020-05-23T12:31:14Z",
   "region": "us-west-2",
   "resources": [ 
        "arn:aws:ecs:us-west-2:111122223333:service/default/servicetest"
   ],
   "detail": {
        "eventType": "ERROR", 
        "eventName": "SERVICE_DEPLOYMENT_FAILED",
        "deploymentId": "ecs-svc/123",
        "updatedAt": "2020-05-23T11:11:11Z",
        "reason": "ECS deployment circuit breaker: task failed to start."
   }
}
```

So you can do something like this to filter on service level:

```
  EventBridgeRule:
    Type: "AWS::Events::Rule"
    Properties:
      Name: "<name>"
      Description: "Monitors ECS Deployment State Change for the cluster"
      EventPattern:
        source:
          - "aws.ecs"
        detail-type:
          - "ECS Deployment State Change"
        detail:
          eventName:
            - "SERVICE_DEPLOYMENT_FAILED"
        resources:
          - !GetAtt ServiceDefinition.ServiceArn
      Targets: ...
```
