### ISSUE TITLE
[EKS] [add-on]: Support aws-load-balancer-controller in EKS Add-On

### ISSUE THREAD

**Issue by bhegazy** [aws/containers-roadmap#1378]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
We use [aws-load-balancer-controller](https://github.com/kubernetes-sigs/aws-load-balancer-controller) greatly, it will be great to have it as EKS add-on.

**Which service(s) is this request for?**
EKS

**Comment by mikestef9** [comment]
Hi @bhegazy, we are working on this. Question, assuming you use helm chart to install today, what parameters are you tweaking as part of that (besides the required cluster name)?

**Comment by bhegazy** [comment]
Yep, we use the official helm chart from eks-charts repository, here is the sample helm values that we use:
```
clusterName: k8s-production
ingressClass: aws-lb
serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::xxxxxxx:role/aws-load-balancer-controller
defaultTags:
  environment: production
```
