### ISSUE TITLE
[service] [request]: describe request here

### ISSUE THREAD

**Issue by enricoebha** [aws/containers-roadmap#1577]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
What do you want us to build? support for VPC with dedicated tenancy for EKS Clusters

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
We are running in a highly regulated environment. We have a requirement to deploy and implement a specific application on EKS on a special AWS account - where only dedicated tenancy is available. 
When running EKS we encounter the following issue: 
> **Error: The subnet(s) provided belong to a VPC with unsupported tenancy. Only subnets from VPCs with default tenancy are supported**

**Are you currently working around this issue?**
In principle EKS Anywhere could be used but this is not allowed in highly regulated environments. We need native support.

**How are you currently solving this problem?**
We are not using EKS for critical use cases.

**Additional context**
How to reproduce:

1. Create a vpc with dedicated tenancy with 2 public and 2 private subnets
2. run:  `eksctl create cluster --config-file cluster_config.yaml`

expect the error: 

> Error: The subnet(s) provided belong to a VPC with unsupported tenancy. Only subnets from VPCs with default tenancy are supported

Content of cluster_config.yaml

```
apiVersion: eksctl.io/v1alpha5 
kind: ClusterConfig

metadata:
  name: my-test-dedicated
  region: us-east-2

vpc:
  id: "vpc-xxxxxx"
  subnets:
    private:
      us-east-2b:
          id: "subnet-xxxxx"
      us-east-2c:
          id: "subnet-xxxxx"
    public:
      us-east-2a:
          id: "subnet-xxxxx"
      us-east-2b:
          id: "subnet-xxxxx"


nodeGroups:
  - name: ng-dedicated-vpc
```
Note: the VPC id mentioned in the cluster_config.yaml is of dedicated tenancy type.
