### ISSUE TITLE
[EKS] [IPv6 on instance TGs]: Add IPv6 support to instance-type target groups for EKS support

### ISSUE THREAD

**Issue by eshicks4** [aws/containers-roadmap#1653]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
Please add IPv6 support to instance-type target groups so that we can use EKS cluster autoscaling groups with ALBs/NLBs.

**Which service(s) is this request for?**
EKS, ELBs

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
EKS creates an autoscaling group onto which we can attach target groups; however, the new IPv6-based clusters don't bind NodePorts to the EC2 nodes' IPv4 IPs.  We have dual-stack ELBs and IPv6-enabled EKS clusters but seem to be missing that connecting piece in-between.

**Are you currently working around this issue?**
We aren't.  We're currently stuck with IPv4 clusters.

**Additional context**
An alternative could be to make EKS clusters dual-stack so we can use the ipFamilies & ipFamilyPolicy features.  IPv6-only would be the default to avoid IP exhaustion but we could selectively bind IPv4 IPs as-needed.

**Attachments**
N/A

**Comment by eshicks4** [comment]
See also case #9628572941

**Comment by mikestef9** [comment]
Hey @eshicks4 this first needs to implemented by ALB and NLB. As called out [here](https://github.com/aws/containers-roadmap/issues/835#issuecomment-1006804864), ALB and NLB only support IP targeting mode for IPv6. Once they support instance mode, we can add support in the AWS Load Balancer Controller. 

Any reason you can't use IP targeting mode?

**Comment by eshicks4** [comment]
My understanding was that IP targeting mode required that you knew the IPs you would be targeting.  Since the cluster is autoscaled and my service's target is running on all nodes as a daemonset, couldn't that list change?

**Comment by mikestef9** [comment]
That's the job of the AWS LB Controller. It watches service endpoints in the cluster and auto updates ALB/NLB target groups with the latest list of pod IP addresses.

**Comment by eshicks4** [comment]
Ok I think I have this design working - at least on my existing IPv4 setup.  I'll need to rebuild to try it on an IPv6-only cluster.

One question, though, as this process involved quite a bit more than my original design.  What kinds of benefits does it provide over a more simple one that just uses an instance-based TG (with IPv6 support) to connect an NLB to the cluster's autoscaling group?

Thanks

**Comment by mikestef9** [comment]
Instance mode load balancer can potentially go through an additional instance hop before the traffic gets to the pod. This adds a higher latency as compared to the case where load balancer can send the traffic directly to the pods. This is possible because VPC CNI directly used VPC IP addresses, so ALB/NLB can send traffic directly to pods and skip node ports and kube-proxy.

**Comment by eshicks4** [comment]
That makes sense.  Not sure it'll help as much with our cluster as everything needs to funnel through Envoy 1st but I can certainly see the benefit for a less specialized cluster with a lot of individual load balancers.

This is sounding more like an ELB feature request.  Should I switch it over to their queue instead?

**Comment by stevehipwell** [comment]
> Instance mode load balancer can potentially go through an additional instance hop before the traffic gets to the pod. This adds a higher latency as compared to the case where load balancer can send the traffic directly to the pods. This is possible because VPC CNI directly used VPC IP addresses, so ALB/NLB can send traffic directly to pods and skip node ports and kube-proxy.

@mikestef9 don't forget that with instance mode you need the extra complexity of external traffic policy set to local if you have compliance policies for public traffic.

@eshicks4 assuming you're using the [AWS Load Balancer Controller](https://kubernetes-sigs.github.io/aws-load-balancer-controller/latest/) (which you should be as the the in tree controller is deprecated) either [ALB IP backed ingress](https://kubernetes-sigs.github.io/aws-load-balancer-controller/latest/guide/ingress/spec/) or [NLB IP backed ingress controller services](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.4/guide/service/nlb/) are the simplest solution.

**Comment by eshicks4** [comment]
@stevehipwell while that may be the simplest solution that currently works for IPv6, I'm not sure I'd call it the simplest overall.  Envoy runs as a daemonset in Project Contour's design so it's going to route to all available nodes anyway.  An NLB configured to route to a static NodePort and auto-updated by the autoscaler doesn't require an ELB controller deployment or any of the IAM role setup that goes along with it.  It works perfectly with IPv4 so, once IPv6 support is added to instance-based target groups, the only real benefit the controller has for us is the direct IP routing that bypasses kube-proxy.

**Comment by stevehipwell** [comment]
@eshicks4 I'd suggest that you could switch Contour to use deployments for Envoy and nlb-ip service annotations; this will allow you to use IPv6 and have a HA ingress (see pod readiness gates). I'm sure there are some limited cases where the daemonset and instance mode is better but I can't think of many cases where the pros outweigh the cons? Obviously you might have some of these so this is just a friendly suggestion.

**Comment by eshicks4** [comment]
@stevehipwell Just the reduction in complexity really. (fewer moving parts to break, etc.)  There may be other reasons but, in our case, Kubernetes is still pretty new and we just have more people familiar with AWS.  That said, I have it all working & documented with the in-cluster ELB controller and no real reason to switch back since there are benefits to using it.  That's why I'm thinking it's best to move this over to the ELB team's feature request bucket instead.

**Comment by yann-soubeyrand** [comment]
Helllo,

We’re more or less in the same situation as @eshicks4.

We’d like to attach our ingress nodes autoscaling group to our load balancer target group. The reason why we’d like to do so is the same: reduction of the complexity (no need to deploy the load balancer controller, one less piece which could break, etc).

Another reason is that, currently, the load balancer controller doesn’t handle the case where two clusters are behind the same target group, which is how we do some blue/green upgrades.

Also, to avoid the additional hop when using instance type target groups and node ports, we deploy our ingress controllers using host ports.

**Comment by plaisted** [comment]
I've been struggling to get the suggested alternative (ip based) solution working with ipv6. Are there guidelines anywhere for troubleshooting this? Logs from `aws-load-balancer-controller` seem okay without errors, The load balancer and target group are created but targets always stay unhealthy. Routing table has ipv6 routes, NACL are fully open for ipv4/v6, security groups wide open to test (in addition to rules created by the controller). I have latest EKS / CNI / controller versions. I have tried ALB / NLB and both have same result and have attempted to hit the service ipv6 endpoints directly as well from the EKS nodes and get refused. Service works perfect with a `kubectl port-forward`.


service description
```yaml
Name:                     <name>
Namespace:                <namespace>
Labels:                   app.kubernetes.io/instance=<namespace>
Annotations:              service.beta.kubernetes.io/aws-load-balancer-ip-address-type: dualstack
                          service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
                          service.beta.kubernetes.io/aws-load-balancer-subnets: subnet-<id>, subnet-<id>
Selector:                 <selector>
Type:                     LoadBalancer
IP Family Policy:         SingleStack
IP Families:              IPv6
IP:                       <address>:e8fb::5a07
IPs:                      <address>:e8fb::5a07
LoadBalancer Ingress:     <redacted>.elb.us-east-1.amazonaws.com
Port:                     <unset>  80/TCP
TargetPort:               5000/TCP
NodePort:                 <unset>  30538/TCP
Endpoints:                [<address>:bf0::1a]:5000,[<address>:bf0::1c]:5000
Session Affinity:         None
External Traffic Policy:  Cluster
Events:
  Type    Reason                  Age                From     Message
  ----    ------                  ----               ----     -------
  Normal  SuccessfullyReconciled  26m (x3 over 72m)  service  Successfully reconciled
```
