### ISSUE TITLE
[EKS] [bug]: GenericEphemeralVolume is not working in EKS 1.22

### ISSUE THREAD

**Issue by AhmadMS1988** [aws/containers-roadmap#1788]
We noticed that GenericEphemeralVolume is not working in EKS 1.22 as expected.
The following the is deployment definition: 

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: MICROSERVICE_NAME
  namespace: ENVIRONMENT-MICROSERVICE_NAME
  labels:
    service: MICROSERVICE_NAME
    env: ENVIRONMENT
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      service: MICROSERVICE_NAME
      env: ENVIRONMENT
  template:
    metadata:
      labels:
        service: MICROSERVICE_NAME
        env: ENVIRONMENT
    spec:
      terminationGracePeriodSeconds: 30
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: service
                  operator: In
                  values:
                  - MICROSERVICE_NAME
              topologyKey: kubernetes.io/hostname
      serviceAccountName: MICROSERVICE_NAME-serviceaccount
      securityContext:
        fsGroup: 48
        sysctls:
        - name: net.core.somaxconn
          value: '10240'
      containers:
      - name: MICROSERVICE_NAME
        image: REPOSITORY_URI:TAG
        imagePullPolicy: Always
        env:
        - name: ENVIRONMENT
          value: ENVIRONMENT
        - name: AWS_DEFAULT_REGION
          value: AWS_REGION
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        ports:
        - name: metrics
          containerPort: 80
        livenessProbe:
          httpGet:
            path: /health_check
            port: metrics
          failureThreshold: 3
          periodSeconds: 10
        startupProbe:
          httpGet:
            path: /health_check
            port: metrics
          failureThreshold: 15
          periodSeconds: 5
        resources:
          requests:
            cpu: '0.25'
            memory: 0.25Gi
          limits:
            cpu: '1'
            memory: 1Gi
        volumeMounts:
          - mountPath: /var/python/tmp
            name: MICROSERVICE_NAME-data
      volumes:
        - name: MICROSERVICE_NAME-data
          ephemeral:
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 8Gi
                storageClassName: ebs-csi-gp3-baseline-sc
```
And this is the defination of ebs-csi-gp3-baseline-sc using ebs-csi
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-csi-gp3-baseline-sc
provisioner: ebs.csi.aws.com
parameters:
  type: gp3
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
```
After running the above manifests, the volume that is created is an emptyDir.
I am wondering if there is something wrong with my configurations above, or that GenericEphemeralVolume is not enabled.
GenericEphemeralVolume is beta since 1.21 and marked as enable by default in the upstream[1]
Please your help enabling that if it is not.

[1] https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
