### ISSUE TITLE
[EKS] [Bug]: EKS 1.24 Incompatible with GRPC health probes 

### ISSUE THREAD

**Issue by lareeth** [aws/containers-roadmap#1952]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
Currently the version of `amazon-eks-pod-identity-webhook` that ships as part of EKS, is incompatible with GRPC health checks and strips the data from the patch file.

**Which service(s) is this request for?**
EKS 1.24

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
We are unable to use native GRPC healthchecks but you get the following error when using an IAM role

```
The Pod "test-grpc" is invalid: spec.containers[0].readinessProbe: Required value: must specify a handler type
```

The patch file thats generated is

```
...
	"readinessProbe": {
		"timeoutSeconds": 1,
		"periodSeconds": 10,
		"successThreshold": 1,
		"failureThreshold": 3
	},
...
```
Instead of
```
...
	"readinessProbe": {
		"grpc": {
			"port":80,
			"service":""
		},
		"timeoutSeconds": 1,
		"periodSeconds": 10,
		"successThreshold": 1,
		"failureThreshold": 3
	},
...
```

**Are you currently working around this issue?**
Using http or exec healthchecks

**Additional context**
Please also see: https://github.com/aws/amazon-eks-pod-identity-webhook/issues/165

**Comment by thomaschaaf** [comment]
@mikestef9 do you happen to know if eks 1.25 is using the new version of the dependency?

**Comment by vipin-mohan** [comment]
@thomaschaaf - EKS 1.25 contains the fix for this issue. We have also backported this fix to EKS 1.24.

**Comment by thomaschaaf** [comment]
@vipin-mohan  has the 1.24 fix been rolled out already or will it be rolled out in the coming weeks?

**Comment by lareeth** [comment]
@vipin-mohan can you provide a source for this? As I'm running EKS 1.25 and still having this issue

**Comment by nckturner** [comment]
@lareeth did you check on a new cluster?  I believe its fixed on new clusters and old clusters will be fixed soon, but let us know if you see differently.

**Comment by lareeth** [comment]
I have only verified on existing 1.24 and 1.25 clusters, will validate tomorrow on a fresh 1.24 and 1.25 cluster

**Comment by nckturner** [comment]
@lareeth Any Update?

**Comment by rodrigorfk** [comment]
Hi there, I was facing similar issue, however in my case the root cause does not seem to be related to the `amazon-eks-pod-identity-webhook`, I was able to successfully create a pod with a `grpc` readiness/liveness probe, I've tested it both on a newly created EKS 1.24 cluster and also on an existing cluster upgraded from 1.23 and now running 1.24 platform version `eks.4`.
In my case, I was able to narrow down the mutating webhook from the `aws-load-balancer-controller` as the culprit, on my tests, grpc probes only works if the that controller is not installed in the cluster, for reference, I've reported this issue under https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/3117. Were you also running the `aws-load-balancer-controller` in the clusters you were testing the grpc probe?

**Comment by rodrigorfk** [comment]
@thomaschaaf Thanks for confirming, that is an interesting situation then, we have a few EKS clusters that were recently upgraded to EKS 1.24 platform version `eks.4`, as long we don't have the mentioned controller/webhook installed, gRPC probes are working fine and the pods are being created with the expected `grpc` spec in the readiness, liveness and startup probes.

**Comment by lareeth** [comment]
@rodrigorfk are you using IAM roles with these pods/deployments?

As this issue is only specific to if you have `eks.amazonaws.com/role-arn` attached to the service account they use, otherwise grpc healthchecks work fine.

**Comment by rodrigorfk** [comment]
@lareeth , thanks for pointing that out, I was not initially testing it with an IAM role defined in the ServiceAccount.
I've just made another test using it and it still working fine in my case, here is the definition of the pod created out of the Deployment:

```yaml
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::000000000000:role/some-podinfo
  name: podinfo
---
apiVersion: v1
kind: Pod
metadata:
  name: podinfo-65b8db99f6-mbhzw
spec:
  containers:
  - command:
    - ./podinfo
    - --port=9898
    - --grpc-port=7777
    env:
    - name: AWS_STS_REGIONAL_ENDPOINTS
      value: regional
    - name: AWS_DEFAULT_REGION
      value: eu-west-1
    - name: AWS_REGION
      value: eu-west-1
    - name: AWS_ROLE_ARN
      value: arn:aws:iam::000000000000:role/some-podinfo
    - name: AWS_WEB_IDENTITY_TOKEN_FILE
      value: /var/run/secrets/eks.amazonaws.com/serviceaccount/token
    image: ghcr.io/stefanprodan/podinfo
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 2
      httpGet:
        path: /healthz
        port: 9898
        scheme: HTTP
      initialDelaySeconds: 10
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
    name: podinfo
    ports:
    - containerPort: 9898
      name: web
      protocol: TCP
    readinessProbe:
      failureThreshold: 2
      grpc:
        port: 7777
        service: ""
      initialDelaySeconds: 10
      periodSeconds: 10
      successThreshold: 2
      timeoutSeconds: 5
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-fb6f5
      readOnly: true
    - mountPath: /var/run/secrets/eks.amazonaws.com/serviceaccount
      name: aws-iam-token
      readOnly: true
  securityContext:
    fsGroup: 1001
    runAsGroup: 1001
    runAsUser: 1001
  serviceAccount: podinfo
  serviceAccountName: podinfo
  terminationGracePeriodSeconds: 120
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: aws-iam-token
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          audience: sts.amazonaws.com
          expirationSeconds: 86400
          path: token
  - name: kube-api-access-fb6f5
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
```
In my case the `amazon-eks-pod-identity-webhook` has worked as expected and added the env variables, volumes and mounts to the pod spec.

**Comment by lareeth** [comment]
Are you deploying the pod directly? Or through a deployment/replica set? As it works if its just a pod.

Can you run this example template, it contains a deployment template and service account template, the pod it launches is etc so its safe to run.

```
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: grpc-healthcheck-test
  labels:
    app: etcd-with-grpc
  annotations:
    eks.amazonaws.com/role-arn: dummy-text

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-healthcheck-test
  labels:
    app: grpc-healthcheck-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpc-healthcheck-test
  template:
    metadata:
      labels:
        app: grpc-healthcheck-test
    spec:
      serviceAccount: grpc-healthcheck-test
      containers:
      - name: etcd
        image: registry.k8s.io/etcd:3.5.1-0
        command: [ "/usr/local/bin/etcd", "--data-dir",  "/var/lib/etcd", "--listen-client-urls", "http://0.0.0.0:2379", "--advertise-client-urls", "http://127.0.0.1:2379", "--log-level", "debug"]
        ports:
        - containerPort: 2379
        livenessProbe:
          grpc:
            port: 2379
          initialDelaySeconds: 10

```
