### ISSUE TITLE
[EKS] [BUG]: Windows Managed Node Groups; On creation removes eks:kube-proxy-windows group from aws-auth configmap

### ISSUE THREAD

**Issue by ChrisMcKee** [aws/containers-roadmap#1977]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
When a new Windows Managed Node Group is created with an existing role name set EKS updates the aws-auth config map in kube-system with the worker-node groups roles and group permissions.
For the managed windows nodes it doesn't differentiate and is subsequently removing the `eks:kube-proxy-windows` group making the node group useless.

**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
~

**Are you currently working around this issue?**
Scripting re-setting the configmap to its proper state.

**Additional context**
As with #1969 the node group is treated as healthy even though it can't start any pods as it can't assign an IP

**Comment by mikestef9** [comment]
Are you using the same IAM role for Windows and Linux managed node group? We strongly recommend separate roles, because different Kubernetes permissions (Windows requires the additional kube proxy permission) are required.

**Comment by ChrisMcKee** [comment]
We're using two separate roles

```yaml
**- groups:
  - system:bootstrappers
  - system:nodes
  rolearn: arn:aws:iam::xxx:role/prod-eks-xxx-cluster_workerinstance_role
  username: system:node:{{EC2PrivateDNSName}}
- groups:
  - system:bootstrappers
  - system:nodes
  - eks:kube-proxy-windows
  rolearn: arn:aws:iam::xx:role/prod-eks-xx-cluster_nt_workerinstance_role
  username: system:node:{{EC2PrivateDNSName}}
```

Its the "NT" role its removing the group from everytime
