### ISSUE TITLE
[service] [request]: Support label eks.amazonaws.com/instance-bandwidth 

### ISSUE THREAD

**Issue by sheetaljoshi** [aws/containers-roadmap#2007]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
Please add a label for instance-bandwidth. Similar to this issue for Karpenter https://github.com/aws/karpenter/pull/3432 I would suggest we use units to be megabits instead of megabytes (similar to instance-memory), as Kubernetes only supports integer comparison for node selector operators.

**Which service(s) is this request for?**
EKS, MNG

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
When this implemented CX can use this field in their Pod manifest to node affinity:
```yaml
   nodeAffinity:
     requiredDuringSchedulingIgnoredDuringExecution:
       nodeSelectorTerms:
       - key: karpenter.sh/instance-network-bandwidth
          operator: Gt
          values: [ 10000 ] // Node must have > 10gigabit connection 
```
This can be very helpful for AI/ML and streaming workloads that require high bandwidth and can benefit from compute isolation. 

**Are you currently working around this issue?**
Currently customers can use instance-type label selectors but it is hard to keep track off.

**Additional context**
Anything else we should know?

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)
