### ISSUE TITLE
[EKS] [BUG]: certificate signing requests are not issued if the request object starts with `csr-`

### ISSUE THREAD

**Issue by antoineco** [aws/containers-roadmap#2079]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**

Context: https://docs.aws.amazon.com/eks/latest/userguide/cert-signing.html

When a `CertificateSigningRequest` object is created with a name including the prefix `csr-`, the EKS control plane silently discards it and doesn't sign the request

**Which service(s) is this request for?**

EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**

I believe this should be either fixed or documented, because:

1. It's very obscure.
1. Prefixing the name of a CSR with "csr-" feels natural enough that a lot of people might run into this issue, and potentially waste a lot of time troubleshooting it.

**Are you currently working around this issue?**

Issue certificate signing requests with names that do start with `csr-`.

**Additional context**

\-

**Attachments**

\-

**Comment by DanielCKennedy** [comment]
What do you mean that it "discards" it? Does the status stay in a "pending" or "approved" state or does it get removed?

**Comment by DanielCKennedy** [comment]
For more context, the default kubelet-serving CSR's created by nodes have a ["csr-" prefix](https://github.com/kubernetes/kubernetes/blob/76eefd3a0129cd3f1845c94f485dc6f112488274/staging/src/k8s.io/client-go/util/certificate/csr/csr.go#L64C3-L64C3) and those are processed just fine in EKS. As far as I know that prefix isn't used as a keyword or cause any special behavior.

**Comment by antoineco** [comment]
I'm on the latest version: 1.27.

The CSR remains in the "Approved" state after being approved by an admin. Its status never changes to "Approved, Issued", and no event or additional status are being emitted by the control plane.
The exact same CSR created with `csr-` removed from the name transitions to "Approved, Issued" immediately after approval.

Correct, kubelet does create CSRs objects prefixed with `csr-`, which is what let me to use that pattern in the first place (I'm adding a Virtual Kubelet to by cluster).
There is however one major difference: kubelet uses the `kubernetes.io/kubelet-signing` signerName, which EKS no longer supports for certificates which aren't issued to EC2 instances (so not an option for Virtual Kubelet).

The issue can be reproduced **consistently**. It wasn't a one off.

**Comment by antoineco** [comment]
To make the issue easier to reproduce, I'm attaching two copies of the _same_ CSR object, where only the `metadata.name` attribute differs.

### Resource manifests

```yaml
# csr-mynode.yaml

apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: csr-mynode
spec:
  signerName: beta.eks.amazonaws.com/app-serving
  usages:
  - digital signature
  - server auth
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQmJEQ0NBUklDQVFBd05ERVZNQk1HQTFVRUNnd01jM2x6ZEdWdE9tNXZaR1Z6TVJzd0dRWURWUVFEREJKegplWE4wWlcwNmJtOWtaVHB0ZVc1dlpHVXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQ0FBUjJkYWpEClVLVVZRRlZHWkprU25WVEhwSGR0a1paWlp5QU1lcnJYL2tTU0gzU1hnSmZZQ1A3Z3grZ3NvTTRXa2JhVGdaY1UKMUQ0djRxOXZSWmgvNzRBNW9Id3dlZ1lKS29aSWh2Y05BUWtPTVcwd2F6QnBCZ05WSFJFRVlqQmdnZ1p0ZVc1dgpaR1dDRG0xNWJtOWtaUzVrWldaaGRYUnNnaEp0ZVc1dlpHVXVaR1ZtWVhWMGJDNXpkbU9DSUcxNWJtOWtaUzVrClpXWmhkWFJzTG5OMll5NWpiSFZ6ZEdWeUxteHZZMkZzaHhEOUxOQ2FDcm9BQUFBQUFBQUFBSlBiTUFvR0NDcUcKU000OUJBTUNBMGdBTUVVQ0lEZHBZMVN3TCs0TXRNU1c0b3Z2MWp6LzVoYUNuU1VXTFNNOE1wSGw4eDJRQWlFQQpyamREQUx3SU5PdFk5TURyUDcrMFllRWh2WjAzeXA0MUlyQUVYYXVSZE9jPQotLS0tLUVORCBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0K
```

```yaml
# notcsr-mynode.yaml

apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: notcsr-mynode
spec:
  signerName: beta.eks.amazonaws.com/app-serving
  usages:
  - digital signature
  - server auth
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQmJEQ0NBUklDQVFBd05ERVZNQk1HQTFVRUNnd01jM2x6ZEdWdE9tNXZaR1Z6TVJzd0dRWURWUVFEREJKegplWE4wWlcwNmJtOWtaVHB0ZVc1dlpHVXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQ0FBUjJkYWpEClVLVVZRRlZHWkprU25WVEhwSGR0a1paWlp5QU1lcnJYL2tTU0gzU1hnSmZZQ1A3Z3grZ3NvTTRXa2JhVGdaY1UKMUQ0djRxOXZSWmgvNzRBNW9Id3dlZ1lKS29aSWh2Y05BUWtPTVcwd2F6QnBCZ05WSFJFRVlqQmdnZ1p0ZVc1dgpaR1dDRG0xNWJtOWtaUzVrWldaaGRYUnNnaEp0ZVc1dlpHVXVaR1ZtWVhWMGJDNXpkbU9DSUcxNWJtOWtaUzVrClpXWmhkWFJzTG5OMll5NWpiSFZ6ZEdWeUxteHZZMkZzaHhEOUxOQ2FDcm9BQUFBQUFBQUFBSlBiTUFvR0NDcUcKU000OUJBTUNBMGdBTUVVQ0lEZHBZMVN3TCs0TXRNU1c0b3Z2MWp6LzVoYUNuU1VXTFNNOE1wSGw4eDJRQWlFQQpyamREQUx3SU5PdFk5TURyUDcrMFllRWh2WjAzeXA0MUlyQUVYYXVSZE9jPQotLS0tLUVORCBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0K
```

### Procedure

1. Create both CSRs.

    ```sh
    kubectl create -f csr-mynode.yaml
    ```

    ```sh
    kubectl create -f notcsr-mynode.yaml
    ```

1. Verify that they were created.

    ```console
    $ kubectl get csr
    NAME            SIGNERNAME                           REQUESTOR   CONDITION
    csr-mynode      beta.eks.amazonaws.com/app-serving   username    Pending
    notcsr-mynode   beta.eks.amazonaws.com/app-serving   username    Pending
    ```

1. Approve both CSRs.

    ```sh
    kubectl certificate approve csr-mynode
    ```

    ```sh
    kubectl certificate approve notcsr-mynode
    ```


1. Verify their status one more time.

    ```console
    $ kubectl get csr
    NAME            SIGNERNAME                           REQUESTOR   CONDITION
    csr-mynode      beta.eks.amazonaws.com/app-serving   username    Approved
    notcsr-mynode   beta.eks.amazonaws.com/app-serving   username    Approved,Issued
    ```

1. Notice how any approved CSR with a name including the `csr-` prefix remains in the "Approved" state forever, while CSRs with a different naming scheme become "Approved,Issued".
