### ISSUE TITLE
[service] [request]: ECS console to show scheduled task triggered by EventBridge Rule and EventBridge Scheduler

### ISSUE THREAD

**Issue by rickychew77** [aws/containers-roadmap#2151]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
To show scheduled task that was triggered by EventBridge Rule and EventBridge Scheduler. We are using AWS CoPilot CLI to handle our ECS deployment and specifically using `type: Scheduled Job` for our copilot deployment.

**Which service(s) is this request for?**
ECS, Scheduled Task

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
I've tried to deploy scheduled job using AWS CoPilot CLI and expecting for the deployed job to show up as `Scheduled Tasks` in AWS ECS console but it is not. When I check in EventBridge Rule, it is there. 
When the schedule/cron matched, it only appears as task in ECS console only, meaning if the schedule/cron is not matched, there is nothing to see in AWS console.

**Are you currently working around this issue?**
Nope.

**Additional context**
NA

**Attachments**
```
name: <job_name>
type: Scheduled Job

on:
  schedule: "50 06 21 09 *" 

image:
  location: <ECR>

cpu: 256       # Number of CPU units for the task.
memory: 512    # Amount of memory in MiB used by the task.
```
![image](https://github.com/aws/containers-roadmap/assets/41740185/633faf98-8035-42cf-9489-4cd20444da94)

![image](https://github.com/aws/containers-roadmap/assets/41740185/bbdea5d5-2452-4ed3-9e25-3fe8837dd4e4)

Reference from AWS Copilot issue:
https://github.com/aws/copilot-cli/issues/3077#issuecomment-1710487585
