### ISSUE TITLE
[EKS] [request]: PodDisruptionBudget for efs-csi-controller

### ISSUE THREAD

**Issue by dpiddock** [aws/containers-roadmap#2154]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
Please could you add a PodDisruptionBudget for the `efs-csi-controller`

**Which service(s) is this request for?**
EKS addon `aws-efs-csi-driver`

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
To not have all the `efs-csi-controller`s terminated/unavailable at once.

**Are you currently working around this issue?**
Manually installing a PDB:
```yaml
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: efs-csi-controller-temp
  namespace: kube-system
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: efs-csi-controller
      app.kubernetes.io/instance: aws-efs-csi-driver
      app.kubernetes.io/name: aws-efs-csi-driver
```

**Additional context**
The similar addon `aws-ebs-csi-driver` creates a pod disruption budget for the `ebs-csi-controller`.

Currently using `aws-efs-csi-driver` addon version v1.5.8-eksbuild.1 with EKS 1.26

**Attachments**
