### ISSUE TITLE
[ECS] [CloudFormation]: CloudFormation support for GPUs in a resourceRequirements field

### ISSUE THREAD

**Issue by lnetherton** [aws/containers-roadmap#223]
**Tell us about your request**
I want to run containers that use the GPU, using the [ECS-optimised AMI for GPUs](http://docs.amazonaws.cn/en_us/AmazonECS/latest/developerguide/ecs-optimized_AMI.html). I also want to be able to describe my task definition in CloudFormation using the [ContainerDefinitions property of the AWS::ECS::TaskDefinition](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ecs-taskdefinition-containerdefinitions.html) resource type.

**Which service(s) is this request for?**
ECS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Even though ECS [now supports](https://aws.amazon.com/blogs/compute/scheduling-gpus-for-deep-learning-tasks-on-amazon-ecs/) running tasks that are GPU-enabled, the task definition must be submitted via the CLI. This is because the CLI [supports the "resourceRequirements" field](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-gpu.html). There seems to be no such support yet for CloudFormation.

**Are you currently working around this issue?**
I am forcing the default docker runtime to `nvidia` in the `/etc/sysconfig/docker` file.

**Additional context**
My guess is that the CF syntax should end up something like this:
```
    Type: AWS::ECS::TaskDefinition
    Properties:
      ContainerDefinitions:
      - name: my_task
        resourceRequirements:
          type: GPU
          value: 1
```
or this:
```
    Type: AWS::ECS::TaskDefinition
    Properties:
      ContainerDefinitions:
      - name: my_task
        gpu: 1
```
