### ISSUE TITLE
[EKS] [request]: Add default toleration for Pod identity agent add-on

### ISSUE THREAD

**Issue by ssup2** [aws/containers-roadmap#2261]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
Please add default toleration for Pod identity agent add-on
```
tolerations: 
- operator: Exists
```

**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Pod identity agent add-on aren't deploying on all nodes due to node taints and lack of default tolerations.

**Are you currently working around this issue?**
None

**Additional context**
None

**Attachments**
Similar Issue : https://github.com/aws/containers-roadmap/issues/2195

**Comment by mikestef9** [comment]
tolerations is an available field in the configuration schema for the add-on. Here is an example defining the add-on with CloudFormation that sets a toleration to tolerate anything

```
  EKSPodIdentityAgent:
    Type: AWS::EKS::Addon
    Properties:
      AddonName: "eks-pod-identity-agent"
      AddonVersion: "v1.1.0-eksbuild.1"
      ClusterName: my-cluster
      ConfigurationValues: |-
        resources:
          limits:
            memory: 20Mi
          requests:
            cpu: 10m
            memory: 20Mi
        tolerations:
          - operator: Exists
      ResolveConflicts: "OVERWRITE"
```
