### ISSUE TITLE
[ECS] [Feature Request]: Allow to specify Log Group for `containerInsights`

### ISSUE THREAD

**Issue by r-heimann** [aws/containers-roadmap#2315]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**

Currently it is not possible to assign a Log Group to an `AWS::ECS::Cluster` with enabled `containerInsights`. This causes the cluster to create a new CloudWatch Log Group. The automatically created Log Group has the following naming scheme:

`/aws/ecs/containerinsights/{ClusterName}/performance`

**Which service(s) is this request for?**

ECS (Fargate) and CloudFormation/CDK

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**

Currently you have to do this:

```yaml
AWSTemplateFormatVersion: 2010-09-09
Description: ECS Cluster example

Resources:
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterSettings:
        - Name: containerInsights # <-- will automatically create a log group
          Value: enabled
      CapacityProviders:
        - FARGATE

  ECSClusterLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/ecs/containerinsights/${ECSCluster}/performance"
```

This will create a Log Group that `containerInsights` uses, including tags and other options a user wants the log group to have. It would be better if a user can directly specify a non-default log group for the `containerInsights` in the GUI and using the API. Lambda, for example, already supports this.

**Are you currently working around this issue?**

See workaround above.

**Additional context**

\-

**Attachments**
\-
