### ISSUE TITLE
[EKS] [request]: Be able to config zipkin address in Advance configuration of solo-io_istio-distro addon

### ISSUE THREAD

**Issue by xiangyanw** [aws/containers-roadmap#2338]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**

I have deployed solo-io_istio-distro via EKS addon. I want to collector Istio tracing data by ADOT. But I am not able to configure the zipkin address in istio-system/istio configmap by EKS addon advance configuration. Since this parameter is not available in the schema.

Below is the config item to be updated in istio-system/istio configmap.

`data.defaultConfig.tracing.zipkin.address`

```
apiVersion: v1
data:
  mesh: |-
    defaultConfig:
      discoveryAddress: istiod.istio-system.svc:15012
      proxyMetadata:
        ISTIO_META_ENABLE_HBONE: "true"
      tracing:
        zipkin:
          address: zipkin-collector.istio-system:9411
```

**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**

Be able to configure zipkin address in EKS addon advance configuration. Otherwise I have to update the configmap directly. This can be overwritten if I upgrade my addon next time.

**Are you currently working around this issue?**

I updated the istio-system/istio configmap inside the Kubernetes cluster directly.

**Additional context**
No

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)
