### ISSUE TITLE
[EKS] [request]: Support TokenRequestProjection

### ISSUE THREAD

**Issue by wadey** [aws/containers-roadmap#238]
**Tell us about your request**
Kubernetes 1.12 moved TokenRequestProjection into beta, but this feature does not appear to be enabled in EKS 1.12. Can you please enable it?

**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
I would like to use TokenRequestProjection to get a token bound to the specific pod. I can then use this token with other external services to prove pod identity.

**Are you currently working around this issue?**
It is very hard to prove pod identity without this feature.

**Additional context**
It looks like #23 mentions building off of TokenRequestProjection to provide IAM roles per pod. So it would make sense to enable this feature so that #23 can use it as well.

I attempted to test this feature with EKS 1.12 by running the example pod described here: https://kubernetes.io/docs/concepts/storage/volumes/#projected

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: sa-token-test
spec:
  containers:
  - name: container-test
    image: busybox
    volumeMounts:
    - name: token-vol
      mountPath: "/service-account"
      readOnly: true
  volumes:
  - name: token-vol
    projected:
      sources:
      - serviceAccountToken:
          audience: api
          expirationSeconds: 3600
          path: token
```

It gave me the following error:

    MountVolume.SetUp failed for volume "token-vol" : failed to fetch token: the server could not find the requested resource

**Attachments**
