### ISSUE TITLE
[EKS] [request]: Allow creating auto-mode EKS cluster without built-in node-pools

### ISSUE THREAD

**Issue by aslatter** [aws/containers-roadmap#2510]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
What do you want us to build? I would like to be able to create an auto-mode EKS cluster without either of the built-in node-pools (*general-purpose* or *system*).

**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
What outcome are you trying to achieve, ultimately, and why is it hard/impossible to do right now? What is the impact of not having this problem solved? The more details you can provide, the better we'll be able to understand and solve the problem.

I have a few use-cases where I would like to be able to customize the Karpenter node-pool when using EKS auto-mode, including:

* Supplying custom tags for compute resources
* Using separate VPC subnets/security-groups for EKS nodes and the EKS-managed-control-plane ENIs
* Applying absolute resource-limits on EC2 capacity used by a cluster
* Use specific EC2 instance-types (or spot instances) for development/prototype clusters

I can create a custom Karpenter node-class and/or node-pool to meet all of these needs, and I can supply the node-pool a non-zero weight so that is prioritized during scheduling.

However I don't seem to be able to disable the built-in node-pools. This means that if for whatever reason Karpenter is unable to schedule a workload onto my custom node-pool (say, because my specified resource-limits were reached) the workload runs the risk of being scheduled onto the built-in node-pool.

This runs the risk of workloads running on mis-tagged resources, running on the wrong subnet with the wrong security-groups, and incurring excess cost.

I tried creating a cluster with *computeConfig.nodePools* set to an empty array (or not set) and received the error:

`An error occurred (InvalidParameterException) when calling the CreateCluster operation: When Compute Config nodeRoleArn is not null or empty, nodePool value(s) must be provided.`

**Are you currently working around this issue?**
How are you currently solving this problem? Not yet using auto-mode

**Additional context**
Anything else we should know?

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

**Comment by mikestef9** [comment]
This is already possible and definitely a supported configuration. You need to leave both `nodePools` and `nodeRoleArn` empty. The nodeRoleArn in the EKS API only applies to built-in node pools. If only using custom nodePools, you need to manually create the AccessEntry so those nodes can join the cluster. Ex (using CFN)

```
  EKSAutoNodeRoleAccessEntry:
    Type: AWS::EKS::AccessEntry
    Properties:
      ClusterName: myClusterName
      PrincipalArn: myNodeRoleArn
      Type: "EC2"
      AccessPolicies:
        - AccessScope:
            Type: cluster
          PolicyArn: arn:aws:eks::aws:cluster-access-policy/AmazonEKSAutoNodePolicy
    DependsOn: [ EKSCluster ] # previously defined EKS Cluster

```

Then reference this node role Arn in the `role` field of the `NodeClass` (you'll also need to define your own custom `NodeClass`)
