### ISSUE TITLE
[EKS] [request]: Add toleration for each Amazon CloudWatch Observability EKS add-on components

### ISSUE THREAD

**Issue by loganmzz** [aws/containers-roadmap#2515]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
https://github.com/aws/containers-roadmap/issues/2195 has added tolerations for many worload (e.g. `dcgm-exporter`) but:

- Not applied on all ones (e.g. `controller-manager`)
- Applied widely where it shouldn't make sense (e.g. `fluentbit`) 

**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
In my context, any workload should be assigned a "node pool" (EKS node group or Karpenter-managed), while I still want to monitor all nodes.

**Are you currently working around this issue?**
I manually patched `controller-manager` deployment:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: amazon-cloudwatch
  name: amazon-cloudwatch-observability-controller-manager
spec:
  template:
      tolerations:
      - effect: NoSchedule
        key: dedicated
        operator: Equal
        value: monitoring
```

**Additional context**
N/A

**Attachments**
N/A
