### ISSUE TITLE
[EKS][auto mode] Workloads fail due to inability to locate kube-dns service

### ISSUE THREAD

**Issue by truongnht** [aws/containers-roadmap#2546]
In typical system we deploy, coredns (kube-dns) is installed in kube-system namespace which our observability related services like Loki (loki-gateway) and Tempo (tempo-gateway) depend on for resolving its related services. Now with auto-mode enabled, we donot install coredns addons and therefore get into the service name resolution issues.

**Comment by oliviassss** [comment]
@truongnht hi, thanks for the info. As a workaround you can create a dummy kube-dns service in your cluster to unblock.
For your application, can you provide more info on how it "locate" the kube-dns service? is it through a `nslookup` or some k8s api?

**Comment by wimspaargaren** [comment]
Hello, I'm facing the same issue. Loki gateway seems to be basically an nginx container with a specific config. In order to resolve DNS for proxy passes within Kubernetes it sets the `resolver` field (by default) as follows:
```
resolver kube-dns.kube-system.svc.cluster.local.;
```
Not familiar with the loki repo, but this seems very similar to what appears in the `loki-gateway` configmap (which contains the nginx conf): https://github.com/grafana/loki/blob/main/production/ksonnet/loki/gateway.libsonnet

I've tried your suggestion by applying a dummy kube-dns service (basically a copy paste of what core dns creates):
```YAML
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "9153"
    prometheus.io/scrape: "true"
  labels:
    eks.amazonaws.com/component: kube-dns
    k8s-app: kube-dns
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: CoreDNS
  name: kube-dns
  namespace: kube-system
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: dns
    port: 53
    protocol: UDP
    targetPort: 53
  - name: dns-tcp
    port: 53
    protocol: TCP
    targetPort: 53
  - name: metrics
    port: 9153
    protocol: TCP
    targetPort: 9153
  selector:
    k8s-app: kube-dns
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```

It actually does get an IP, but now I get the following error:
```
2025/02/20 21:53:47 [error] 9#9: send() failed (111: Connection refused) while resolving, resolver: 172.XX.YY.ZZZ:53
```

So my assumption is that the app selector is incorrect, but maybe it's something else. 

@oliviassss any idea what I should adjust here/could try?
