### ISSUE TITLE
EKS Auto Mode starts with 0 nodes & can't schedule new nodes

### ISSUE THREAD

**Issue by hubatish** [aws/containers-roadmap#2557]
When I create an EKS Auto Mode, I get a cluster with no nodes & pods. Then when I try to apply a simple yaml, the deployment fails with pods stuck in Pending state with FailedScheduling events.

Here's the commands I've run:

```
eksctl create cluster --enable-auto-mode=True  --name=my-name --region=my-region  --vpc-nat-mode=Disable --with-oidc=True
kubectl apply -f kubernetes_scale.yaml
```
And kubernetes_scale.yaml is very simple as well:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "kubernetes-scaleup"
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  selector:
    matchLabels:
      name: "kubernetes-scaleup"
  template:
    metadata:
      labels:
        name: "kubernetes-scaleup"
    spec:
      containers:
      - image: k8s.gcr.io/pause:3.1
        name: "kubernetes-scaleup"
        resources:
          requests:
            cpu: "250m"
            memory: "250M"
            ephemeral-storage: "10Mi"
          limits:
            cpu: "250m"
            memory: "250M"
            ephemeral-storage: "10Mi"
      terminationGracePeriodSeconds: 1
      # Add not-ready/unreachable tolerations for X seconds so that node
      # failure doesn't trigger pod deletion.
      tolerations:
      - key: "node.kubernetes.io/not-ready"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 600
      - key: "node.kubernetes.io/unreachable"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 600
```

This works on GKE & AKS with just the create command & setting max-nodes variable. I thought EKS Auto was supposed to be the easy mode to get this working quickly?

My nodeclaims have status UNKNOWN & events like:

```
  Conditions:
    Last Transition Time:  2025-03-06T23:05:15Z
    Message:               object is awaiting reconciliation
    Observed Generation:   1
    Reason:                AwaitingReconciliation
    Status:                Unknown
    Type:                  Initialized
    Last Transition Time:  2025-03-06T23:05:15Z
    Message:               Node not registered with cluster
    Observed Generation:   1
    Reason:                NodeNotFound
    Status:                Unknown
    Type:                  Registered
    Last Transition Time:  2025-03-06T23:05:18Z
    Message:               
    Observed Generation:   1
    Reason:                Launched
    Status:                True
    Type:                  Launched
    Last Transition Time:  2025-03-06T23:05:15Z
    Message:               Initialized=Unknown, Registered=Unknown
    Observed Generation:   1
    Reason:                ReconcilingDependents
    Status:                Unknown
    Type:                  Ready
```
