### ISSUE TITLE
[EKS] [Community Addon cert-manager]: Expose Prometheus values

### ISSUE THREAD

**Issue by kstevensonnv** [aws/containers-roadmap#2584]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
Prometheus metrics are enabled and available by default when installing the addon.
The Prometheus values are not exposed in the addon configuration values.
Can these be exposed.

The values are set here in the [cert-manager helm chart](https://github.com/cert-manager/cert-manager/blob/master/deploy/charts/cert-manager/values.yaml#L514):

```
prometheus:
  servicemonitor:
    enabled: true
```

**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
I want to monitor cert-manager using Prometheus and graph metrics in Grafana.

**Are you currently working around this issue?**
Yes, by manually creating a Service Monitor.

<details>
<summary>cert_manager_service_monitor.yaml</summary>

```yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: cert-manager
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: cert-manager
    app.kubernetes.io/name: cert-manager
  name: cert-manager
  namespace: cert-manager
spec:
  endpoints:
  - honorLabels: false
    interval: 60s
    path: /metrics
    scrapeTimeout: 30s
    targetPort: 9402
  namespaceSelector:
    matchNames:
    - cert-manager
  selector:
    matchExpressions:
    - key: app.kubernetes.io/name
      operator: In
      values:
      - cainjector
      - cert-manager
      - webhook
    - key: app.kubernetes.io/instance
      operator: In
      values:
      - cert-manager
    - key: app.kubernetes.io/component
      operator: In
      values:
      - cainjector
      - controller
      - webhook

```

</details>
