### ISSUE TITLE
[EKS] [request]: add anti-affinity to coredns deployment to schedule pods across AZ

### ISSUE THREAD

**Issue by adaniline-traderev** [aws/containers-roadmap#295]
**Tell us about your request**
By default, CoreDNS deployment does not have an anti-affinity rule to schedule coredns pods across AZ (fault domain). Please add this to the coredns deployment

**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Newly created EKS clusters may run coredns pods on the same node, which makes the service less available

**Are you currently working around this issue?**
You can change coredns deployment after EKS cluster is created, but it would be nice to have it as default

**Comment by whereisaaron** [comment]
(Anti-)affinity is a currently pretty flawed in Kubernetes, in that scheduling becomes highly inefficient. It becomes a scaling problem on large clusters. It also impacts the `cluster-autoscaler` performance. That's why you often see base `kube-system` services like DNS not using them.

On small clusters it is still useful, and would be a valuable option to add to `eksctl`. But it probably ought to be optional because it is not desirable for all users given the performance problems it causes. 

One more efficient approach is to use the `descheduler` to remove duplicates on a node.
https://github.com/kubernetes-incubator/descheduler#removeduplicates

Another simple approach is to run more replicas of services like Core DNS so you are almost guaranteed multiple failure zones. The scheduler has a kind of round-robin behavior that makes starting on the same node unlikely. And rescheduled pods (e.g. from `descheduler`) almost always move to a different node.

https://github.com/kubernetes/kubernetes/issues/72479

> "Pod Affinity/AntiAffinity is causing us a bunch of pain from performance/scalability perspective. Although scheduling SIG has done tremendous effort to improve it, it's still the very significant (most?) factor for scheduling throughput."

https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#what-are-the-service-level-objectives-for-cluster-autoscaler

> "Please note that the above performance can be achieved only if NO pod affinity and anti-affinity is used on any of the pods. Unfortunately, the current implementation of the affinity predicate in scheduler is about 3 orders of magnitude slower than for all other predicates combined, and it makes CA hardly usable on big clusters."

**Comment by bluebenno** [comment]
I have a very small cluster, around a dozen nodes and both instances of coredns are currently running on the same ec2 node. Perhaps I am unlucky today?!

I was following documentation at https://docs.aws.amazon.com/eks/latest/userguide/update-cluster.html.  A possible solution is to update the documentation about adding affinity (at your risk). The stable helm chart has optional anti/affinity.

[unrelated to this request] I think there should be many more replicas of coredns, especially for upgrades.  Current version of coredns is much higher.

**Comment by chapitos** [comment]
We have run at the same problem, and since we are running a very small cluster (3 nodes),  increasing the number of CoreDNS replicas to ensure multiple AZ coverage did not seem as a good solution. We have patched the CoreDNS in a pipeline to include the anti affinity rules.

**Comment by alon-dotan-starkware** [comment]
we also suffering from this issue, currently, we need to patch the CoreDNS deployment manually as post-installation flow, pretty dirty...

**Comment by atulatri** [comment]
We have a cluster with ondemad and spot instances node groups. And we would like coredns on ondemand instance group. I think, Affinity support could help us here.

**Comment by jaimehrubiks** [comment]
Same issue here, we need to patch the deployment, but it is tricky because we install the addon as part of the pipeline with terraform

**Comment by dindurthy** [comment]
We are creating a dedicated node group for core services including EKS addons. Looking at coredns, it looks like affinity/nodeSelector/tolerations are managed fields. What are our options? Looks like we're SOL changing that field and expecting it to persist through upgrade.

**Comment by ipleten** [comment]
in EKS v1.18 if already has podAntiAffinity:
```
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: k8s-app
                  operator: In
                  values:
                  - kube-dns
              topologyKey: kubernetes.io/hostname
            weight: 100
```
But it's `preferredDuringSchedulingIgnoredDuringExecution` which still implies that there is a chance to have all coredns pods on the same node. And there is not way to change that as it's a server-side add-on with managed fields. 
I'd like to have it `requiredDuringSchedulingIgnoredDuringExecution` instead of `preferred...`.
I assume it was done to allow only one node running.

**Comment by Legion2** [comment]
We also have a dedicated nodegroup for infrastructure pods, which includes coredns. The nodegroup is tainted, so only selected pods can be scheduled on the nodes. However, we can not add the required toleration to the coredns pods, because it is a managed field.

**Comment by ChuckNoxis** [comment]
Any updates on this ?

I created an EKS cluster with 2 nodes and the 2 coredns pods are deployed on the same node

**Comment by FernandoMiguel** [comment]
> Any updates on this ?
> 
> I created an EKS cluster with 2 nodes and the 2 coredns pods are deployed on the same node

that will come in coredns v1.9
https://github.com/coredns/helm/pull/61

**Comment by thiagolsfortunato** [comment]
Same issue here.

My managed CoreDNS has PodAntifinity and NodeAffinity setup. When I tried to install the CoreDNS Add-on I got the error:
![Screenshot 2022-12-29 at 17 07 36](https://user-images.githubusercontent.com/11510919/210006410-91c4bb1d-3d32-47f7-9aa3-e274f9aefd09.png)


```
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/os
                operator: In
                values:
                - linux
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
                - arm64
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: k8s-app
                  operator: In
                  values:
                  - kube-dns
              topologyKey: kubernetes.io/hostname
            weight: 100
```

I don't want to overwrite it.

**Comment by bryanasdev000** [comment]
> Same issue here.
> 
> My managed CoreDNS has PodAntifinity and NodeAffinity setup. When I tried to install the CoreDNS Add-on I got the error: ![Screenshot 2022-12-29 at 17 07 36](https://user-images.githubusercontent.com/11510919/210006410-91c4bb1d-3d32-47f7-9aa3-e274f9aefd09.png)
> 
> My CoreDNS config:
> 
> ```
>     spec:
>       affinity:
>         nodeAffinity:
>           requiredDuringSchedulingIgnoredDuringExecution:
>             nodeSelectorTerms:
>             - matchExpressions:
>               - key: kubernetes.io/os
>                 operator: In
>                 values:
>                 - linux
>               - key: kubernetes.io/arch
>                 operator: In
>                 values:
>                 - amd64
>                 - arm64
>         podAntiAffinity:
>           preferredDuringSchedulingIgnoredDuringExecution:
>           - podAffinityTerm:
>               labelSelector:
>                 matchExpressions:
>                 - key: k8s-app
>                   operator: In
>                   values:
>                   - kube-dns
>               topologyKey: kubernetes.io/hostname
>             weight: 100
> ```
> 
> I don't want to overwrite it.

Just for curiosity, which version?

A little bit since I have brought up a new cluster, but AFAIK this is the same what I have running EKS 1.22 and CoreDNS managed v1.8.7-eksbuild.1.

Also, this https://kubernetes.io/docs/tasks/administer-cluster/dns-horizontal-autoscaling/ maybe help as workaround to this issue.

**Comment by bryanasdev000** [comment]
Also with https://aws.amazon.com/blogs/containers/amazon-eks-add-ons-advanced-configuration/, this can be possible now or maybe with self managed too and setting it up externally.

**Comment by thiagolsfortunato** [comment]
> Just for curiosity, which version?
> 
> A little bit since I have brought up a new cluster, but AFAIK this is the same what I have running EKS 1.22 and CoreDNS managed v1.8.7-eksbuild.1.
> 
> Also, this [https://kubernetes.io/docs/tasks/administer-cluster/dns-horizontal-autoscaling/ maybe](https://kubernetes.io/docs/tasks/administer-cluster/dns-horizontal-autoscaling/%C2%A0maybe) help as workaround to this issue.

I'm self managing CoreDNS 1.8.7-eksbuild.1

> Also with https://aws.amazon.com/blogs/containers/amazon-eks-add-ons-advanced-configuration/, this can be possible now or maybe with self-managed too and setting it up externally.

I'm not found how to add nodeAffinity or podAntiAffinity in the `configurationValues` for CoreDNS, which I guess is not supported.

**Comment by yann-soubeyrand** [comment]
Unless I’m mistaken, I confirm what @thiagolsfortunato said, it’s not possible to configure pod anti-affinity using CoreDNS add-on configuration values. It would be great if a simple boolean (or a tristate disabled/soft/hard) setting was available.

**Comment by marksumm** [comment]
@yann-soubeyrand I reached the same conclusion when I looked into it last week.  At the risk of stating the obvious, this is really not great for high availability of the coredns service.

**Comment by bryanasdev000** [comment]
Related https://github.com/aws/containers-roadmap/issues/1275#issuecomment-1400984818

**Comment by youwalther65** [comment]
I just checked coredns add-on version v1.9.3-eksbuild.3 and the schema has changed a lot compared to previous version v1.9.3-eksbuild.2 and now contains affinity and tolerations! See here:

```yaml
$ aws eks describe-addon-configuration --addon-name coredns --addon-version v1.9.3-eksbuild.3 --query 'configurationSchema' --output text | jq
{
  "$ref": "#/definitions/Coredns",
  "$schema": "http://json-schema.org/draft-06/schema#",
  "definitions": {
    "Coredns": {
      "additionalProperties": false,
      "properties": {
        "affinity": {
          "default": {
            "affinity": {
              "nodeAffinity": {
                "requiredDuringSchedulingIgnoredDuringExecution": {
                  "nodeSelectorTerms": [
                    {
                      "matchExpressions": [
                        {
                          "key": "kubernetes.io/os",
                          "operator": "In",
                          "values": [
                            "linux"
                          ]
                        },
                        {
                          "key": "kubernetes.io/arch",
                          "operator": "In",
                          "values": [
                            "amd64",
                            "arm64"
                          ]
                        }
                      ]
                    }
                  ]
                }
              },
              "podAntiAffinity": {
                "preferredDuringSchedulingIgnoredDuringExecution": [
                  {
                    "podAffinityTerm": {
                      "labelSelector": {
                        "matchExpressions": [
                          {
                            "key": "k8s-app",
                            "operator": "In",
                            "values": [
                              "kube-dns"
                            ]
                          }
                        ]
                      },
                      "topologyKey": "kubernetes.io/hostname"
                    },
                    "weight": 100
                  }
                ]
              }
            }
          },
          "description": "Affinity of the coredns pods",
          "type": [
            "object",
            "null"
          ]
        },
        "computeType": {
          "type": "string"
        },
        "corefile": {
          "description": "Entire corefile contents to use with installation",
          "type": "string"
        },
        "nodeSelector": {
          "additionalProperties": {
            "type": "string"
          },
          "type": "object"
        },
        "replicaCount": {
          "type": "integer"
        },
        "resources": {
          "$ref": "#/definitions/Resources"
        },
        "tolerations": {
          "default": [
            {
              "key": "CriticalAddonsOnly",
              "operator": "Exists"
            },
            {
              "key": "node-role.kubernetes.io/master",
              "operator": "NoSchedule"
            }
          ],
          "description": "Tolerations of the coredns pod",
          "items": {
            "type": "object"
          },
          "type": "array"
        }
      },
      "title": "Coredns",
      "type": "object"
    },
    "Limits": {
      "additionalProperties": false,
      "properties": {
        "cpu": {
          "type": "string"
        },
        "memory": {
          "type": "string"
        }
      },
      "title": "Limits",
      "type": "object"
    },
    "Resources": {
      "additionalProperties": false,
      "properties": {
        "limits": {
          "$ref": "#/definitions/Limits"
        },
        "requests": {
          "$ref": "#/definitions/Limits"
        }
      },
      "title": "Resources",
      "type": "object"
    }
  }
}
```
It is first supported with EKS v1.24
```yaml
$ aws eks describe-addon-versions --addon-name coredns --kubernetes-version 1.24 --query 'addons[*].addonVersions[*].addonVersion'
[
    [
        "v1.9.3-eksbuild.3",
        "v1.9.3-eksbuild.2",
        "v1.8.7-eksbuild.4",
        "v1.8.7-eksbuild.3",
        "v1.8.4-eksbuild.2"
    ]
]
```

Can someone please check and confirm.

**Comment by jaimehrubiks** [comment]
@youwalther65 
Thanks for notifying!

**Comment by orsenthil** [comment]
@youwalther65 - Looks like your account is allow-listed for internal versions. So you are noticing the internal changes.  The Coredns 1.9.3-eksbuild.3 is not externally released yet, and once released it will be announced at https://docs.aws.amazon.com/eks/latest/userguide/managing-coredns.html and other relevant avenues, including this ticket.

Thank you.

**Comment by bdwyertech** [comment]
[Topology Spread Constraints](https://kubernetes.io/docs/concepts/scheduling-eviction/topology-spread-constraints/) are the correct way to do this, I still do not see this in the add-on schema.

```yaml
topologySpreadConstraints:
  - maxSkew: 1
    topologyKey: topology.kubernetes.io/zone
    whenUnsatisfiable: ScheduleAnyway
    labelSelector:
      matchLabels:
        k8s-app: kube-dns
```

**Comment by marksumm** [comment]
In practice, even with **v1.9.3-eksbuild.3**, if you try to change `preferredDuringSchedulingIgnoredDuringExecution` to `requiredDuringSchedulingIgnoredDuringExecution` in the `podAntiAffinity` section, the add-on update will fail with the incredibly helpful error message "The configuration values provided are invalid".

**Comment by ezhan-codaio** [comment]
> In practice, even with **v1.9.3-eksbuild.3**, if you try to change `preferredDuringSchedulingIgnoredDuringExecution` to `requiredDuringSchedulingIgnoredDuringExecution` in the `podAntiAffinity` section, the add-on update will fail with the incredibly helpful error message "The configuration values provided are invalid".
> 
> Update: My configuration was valid JSON, and valid in terms of the CoreDNS configuration values schema, but invalid for Kubernetes. With a valid configuration, I was able to use `requiredDuringSchedulingIgnoredDuringExecution` in `podAntiAffinity`. Also, since configuration values are merged with the default configuration, I explicitly set `preferredDuringSchedulingIgnoredDuringExecution` to an empty list.

Hi @marksumm, can you share your configuration? I am not able to get it working and keep getting "The configuration values provided are invalid." Thanks in advance!

**Comment by ezhan-codaio** [comment]
> In practice, even with **v1.9.3-eksbuild.3**, if you try to change `preferredDuringSchedulingIgnoredDuringExecution` to `requiredDuringSchedulingIgnoredDuringExecution` in the `podAntiAffinity` section, the add-on update will fail with the incredibly helpful error message "The configuration values provided are invalid".
> 
> Update: My configuration was valid JSON, and valid in terms of the CoreDNS configuration values schema, but invalid for Kubernetes. With a valid configuration, I was able to use `requiredDuringSchedulingIgnoredDuringExecution` in `podAntiAffinity`. Also, since configuration values are merged with the default configuration, I explicitly set `preferredDuringSchedulingIgnoredDuringExecution` to an empty list.

Hi @marksumm, can you share your configuration?

This is mine, and I am currently getting "UnsupportedAddonModification | Amazon EKS was unable to complete the addon operation. The configuration values provided are invalid."
```{"affinity":{"podAntiAffinity":{"preferredDuringSchedulingIgnoredDuringExecution":[],"requiredDuringSchedulingIgnoredDuringExecution":[{"podAffinityTerm":{"labelSelector":{"matchExpressions":[{"key":"k8s-app","operator":"In","values":["kube-dns"]}]},"topologyKey":"kubernetes.io/hostname"},"weight":100}]}},"replicaCount":2}
```

Version `v1.10.1-eksbuild.1`. If I change `requiredDuringSchedulingIgnoredDuringExecution` back to `preferredDuringSchedulingIgnoredDuringExecution` it goes through just fine.

**Comment by kr3cj** [comment]
> [Topology Spread Constraints](https://kubernetes.io/docs/concepts/scheduling-eviction/topology-spread-constraints/) are the correct way to do this, I still do not see this in the add-on schema.

@bdwyertech `toplogySpreadConstraints` is now available in the schema on the latest versions of `coredns` (at least in 1.26). I was able to successfully set the same code you shared via `configurationValues` and it showed up in the deployment manifest afterwards.

**Comment by sjastis** [comment]
Resolving this issue since topologySpreadConstraints support is available starting coredns v1.10.1-eksbuild.2 and v1.9.3-eksbuild.5.

**Comment by samul69** [comment]
@marksumm could you share your json file from you update? i tried what you describe but without any success :(

**Comment by marksumm** [comment]
@samul69 I changed jobs since I wrote my previous comment, but my advice is to check the Kubernetes documentation and pay attention to the differences in inner syntax between `preferredDuringSchedulingIgnoredDuringExecution`  and  `requiredDuringSchedulingIgnoredDuringExecution` i.e. it's not only a matter of changing the first part of the string.

**Comment by kr3cj** [comment]
It took me a lot of trial and error to get the affinity settings to work for me (k8s 1.27, eksctl `0.169.0`, and coredns `v1.10.1-eksbuild.7`). I just wanted to require the pods be on different hosts and different AZs. Sharing my settings in case it helps the next person.

```yaml
addons:
  - name: coredns
    version: latest
    resolveConflicts: overwrite
    configurationValues: |-
      replicaCount: 3
      topologySpreadConstraints:
        # restate default
        - labelSelector:
            matchLabels:
              k8s-app: kube-dns
          topologyKey: topology.kubernetes.io/zone
          maxSkew: 1
          whenUnsatisfiable: ScheduleAnyway
        # add additional one for us
        - labelSelector:
            matchLabels:
              k8s-app: kube-dns
          topologyKey: topology.kubernetes.io/hostname
          maxSkew: 1
          whenUnsatisfiable: ScheduleAnyway
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                # restate defaults
                  - key: kubernetes.io/os
                    operator: In
                    values:
                      - linux
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
                      - arm64
          preferredDuringSchedulingIgnoredDuringExecution: []
            # enabling this would eventually timeout for some reason
            # nodeSelectorTerms:
            #   - matchExpressions:
            #       - key: node-lifecycle
            #         operator: In
            #         values:
            #           - on-demand
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution: []
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: k8s-app
                    operator: In
                    values:
                      - kube-dns
              topologyKey: "kubernetes.io/hostname"
            - labelSelector:
                matchExpressions:
                  - key: k8s-app
                    operator: In
                    values:
                      - kube-dns
              topologyKey: "topology.kubernetes.io/zone"
```

The only section I couldn't get working was the `nodeSelectorTerms`. It would just time out after 25 minutes and respond to checks with `EKS managed addon coredns appears unhealthy! Status: UPDATE_FAILED Issues: [{'Code': 'UnsupportedAddonModification', 'Message': 'Amazon EKS was unable to complete the addon operation. The configuration values provided are invalid.', 'ResourceIDs': None}]`
