### ISSUE TITLE
[ECS, Fargate] CloudFormation support for scheduled tasks with Fargate Launch Type

### ISSUE THREAD

**Issue by coultn** [aws/containers-roadmap#392]
ECS supports scheduled tasks using [CloudWatch events rules](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/scheduled_tasks.html).  This issue is specifically to add CloudFormation support for scheduled tasks when using the Fargate launch type.

**Comment by mildebrandt** [comment]
Isn't this supported already? https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-events-rule.html

For example, to run a task every 20 minutes:
```
apiScheduledTaskRule:
    Type: AWS::Events::Rule
    Properties:
      ScheduleExpression: 'cron(*/20 * * * ? *)'
      State: ENABLED
      Targets:
        - Arn: <your cluster ARN>
          RoleArn: <your task execution role ARN>
          Id: apiScheduledTask
          EcsParameters:
            TaskDefinitionArn: <reference to your task definition>
            LaunchType: FARGATE
            NetworkConfiguration:
              AwsVpcConfiguration:
                SecurityGroups:
                  - <your security groups>
                Subnets:
                  - <your subnets>
```
We do this to regularly run tasks.

Of course, replace `ScheduleExpression` with `EventPattern` for CloudWatch events. Does that do what you're expecting, or am I missing something?
