### ISSUE TITLE
[EKS] [request]: ALB ingress controller wildcard listener rules

### ISSUE THREAD

**Issue by omgapuppy** [aws/containers-roadmap#447]
**Tell us about your request**
Support wildcards in listener rules via aws-alb-ingress-controller.

**Which service(s) is this request for?**
EKS - ALB ingress controller. Related issue on [project repo](https://github.com/kubernetes-sigs/aws-alb-ingress-controller/issues/987)

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
AWS ALB listener rules support wildcards i.e `service-*.example.com` for matching `service-a.example.com` or `service-b.example.com`.

Trying to pass a partial string via `host` to ingress controller is not supported by kubernetes i.e

```
  - host: 'service-*.example.com'
    http:
      paths:
      - path: /*
        backend:
          serviceName: api
          servicePort: 443
```

will result in an error:

```
The Ingress "c" is invalid: spec.rules[1].host: Invalid value: "service-*.example.com": a wildcard DNS-1123 subdomain must start with '*.', followed by a valid DNS subdomain, which must consist of lower case alphanumeric characters, '-' or '.' and end with an alphanumeric character (e.g. '*.example.com', regex used for validation is '\*\.[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
```

This is, in fairness, an expected result as we're trying to pass an invalid DNS record.

Being able to work around this by supplying listener rules, in addition to an exact match, via ingress annotations would be preferable. Much like most ALB configuration is passed to the controller via annotations.

**Are you currently working around this issue?**
We use a wildcard listener as an acceptable security regression in current context, in order to maintain compatibility with `external-dns` controller.

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
      <redacted>
    external-dns.alpha.kubernetes.io/hostname: component-a.example.com
    external-dns.alpha.kubernetes.io/ttl: "60"
    kubernetes.io/ingress.class: alb
   hosts:
      - host: ""
         paths:
          - /*
```

**Additional context**
We're in the process of migrating legacy workloads to EKS, and use weighted r53 DNS records to achieve no downtime traffic shifting of public facing endpoints.

This means we've r53 records like:
  * `service.example.com` pointing to ELB in front of legacy infra
  * `service-eks.example.com` pointing to ALB in front of EKS

The wildcard in listener is needed to allow weighted DNS from `service.example.com` to point at `service-eks.example.com`, as client requests would be routed to `service.example.com` and would fail header checks on ALB with `service-eks.example.com` as the sole listener.

Manual intervention with ALB is not desirable as we'd like to keep EKS & ALB ingress controller as the source of truth / owner.

As we're using `external-dns` controller extensively across r53 zones, explicitly disabling its ability to monitor a select few ingresses within a given cluster would introduce inconsistency to overall workflow.
