### ISSUE TITLE
ECS/Fargate: DesiredCount should be completely optional

### ISSUE THREAD

**Issue by pgarbe** [aws/containers-roadmap#493]
**Tell us about your request**
The `DesiredCount` property should be optional both when creating and updating an ECS service. If it's not defined the default should be the min value of the attached autoscaling (or 0 if there's no autoscaling).
An alternative could be to introduce another property `InitialDesiredCount` which explicitly sets the DesiredCount when the Service gets created.

**Which service(s) is this request for?**
Fargate, ECS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
The problem comes in combination with CloudFormation. As soon as anything changes in the ECS Service Resource (e.g. tags are modified), CloudFormation overwrites the DesiredCount.  But DesiredCount might have changed because of AutoScaling. This can lead to situations where the number of running tasks is suddenly scaled down from e.g. 100 to 2.

**Are you currently working around this issue?**
There's no real workaround , as Cfn does not provide a conditional value based when the stack gets created or updated.

The only thing you can do is to remove the `DesiredCount` property from the CloudFormation template after the application gets the first time deployed.

**Attachments**
Initially opened the ticket at the CloudFormation roadmap [here](https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/187), but got the [hint](https://twitter.com/nickcoult/status/1175159331903262720) that it's actually an ECS issue.

**Comment by jooj123** [comment]
We have added a hack around this to do `aws cli` call to get current `desiredCount` and pass that to CF script (if it exists)

Feels very clunky / error prone and something that should be handled by AWS natively - would love for this to be sorted please 🙏

**Comment by softprops** [comment]
We do something similar passing in a desired count _and_ the number of active services which will be one or zero. so that we leave autoscaling's desired count be when a service has been previously created and to set an initial value if its the first time the service is being created

```yaml
<snip>
Parameters:
  DesiredCount:
    Type: Number
    Description: default number of tasks for a service when a service does not yet exist
  ServiceCount:
    Type: Number
    Description: precise number services with the same name in the same cluster

Conditions:
  ServiceExists:
    !Equals [!Ref ServiceCount, 1]

Resources:
  Service:
    Type: AWS::ECS::Service
    Properties:
      DesiredCount: !If [ServiceExists, !Ref 'AWS::NoValue', !Ref 'DesiredCount']
<snip>
```

the pass the output of the following to our cloud formation deploy command as a parameter override for `ServiceCount`

```sh
aws ecs describe-services \
  --cluster {the-cluster}  \
  --services {the-service \
  --query 'length(services[?status==`ACTIVE`])' --output text
```
