### ISSUE TITLE
[EKS] [request]: Disable anonymous-auth to kube-apiserver

### ISSUE THREAD

**Issue by jessebye** [aws/containers-roadmap#532]
**Tell us about your request**
Add the ability to pass the `--anonymous-auth=false` flag to the `kube-apiserver`. Passing in other arbitrary flags to the apiserver would also be nice, but not as necessary.

**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Several attacks target `kube-apiserver` through anonymous auth. [Billion laughs](https://github.com/kubernetes/kubernetes/issues/83253) is a good example of a very recent attack that could be exploited by anonymous auth.

Disabling anonymous auth completely is a security best-practice and mitigates a whole class of attacks.

**Are you currently working around this issue?**
By keeping our clusters up-to-date with security fixes and protecting the endpoint URLs from public discovery. We could use private API endpoints, but this is complicated due to https://github.com/aws/containers-roadmap/issues/221

**Additional context**
n/a

**Attachments**
n/a

**Comment by szymonpk** [comment]
Can you even run any anonymous actions with EKS? I always believed IAM identity is mandatory when interacting with EKS clusters - https://docs.aws.amazon.com/en_pv/eks/latest/userguide/managing-auth.html.

**Comment by jessebye** [comment]
@szymonpk You _can_ run anonymous actions with EKS. It is possible to completely bypass IAM for user authentication if you wish, it's just common to use IAM for this on EKS.

Here's a test I did demonstrating that Anonymous auth isn't completely disabled:

The `~/.kube/config` looks like this:
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: [redacted]
    server: https://[redacted].[redacted].us-east-2.eks.amazonaws.com
  name: arn:aws:eks:us-east-2:[redacted]:cluster/test
contexts:
- context:
    cluster: arn:aws:eks:us-east-2:[redacted]:cluster/test
    user: arn:aws:eks:us-east-2:[redacted]:cluster/test
  name: dev
current-context: dev
kind: Config
preferences: {}
```

Then running a command, I get a prompt for username/password and enter invalid info (`asdf`):
```
kubectl cluster-info dump
Please enter Username: asdf
Please enter Password: Error from server (Forbidden): nodes is forbidden: User "system:anonymous" cannot list resource "nodes" in API group "" at the cluster scope```

As the error message indicates, I _am_ authenticated as an anonymous user, but get forbidden because the anonymous user doesn't have permissions.
