### ISSUE TITLE
[FARGATE] [SHM]: allow usage of /dev/shm and tmpfs

### ISSUE THREAD

**Issue by taktakpeops** [aws/containers-roadmap#710]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
As a software engineer, I want to deploy a Selenium Grid in ECS Fargate with Chrome and Firefox nodes running in headless mode.

I currently can have only Chrome deployed because it can be configured for not using `/dev/shm`. As far as I know, Firefox headless needs `/dev/shm`.

The idea behind my request is to enable a Fargate task to use `/dev/shm` or `tmpfs` as it's possible in ECS.

**Which service(s) is this request for?**
Fargate

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Currently, for giving access to `/dev/shm` to my container inside a task, I am doing the following in my Cloudformation manifest:

```
SeleniumNodeFirefoxTask:
    Type: "AWS::ECS::TaskDefinition"
    DependsOn: TalpaAccountSeleniumGrid
    Properties:
      Volumes:
        - Name: "shm"
    ContainerDefinitions:
    - MountPoints:
           - ContainerPath: /dev/shm
              SourceVolume: shm
              ReadOnly: false
```

The volume is mounted correctly but Firefox keep failing.

Here is an error message I got from my Firefox container:

```
WARNING: failed to open shm: Permission denied: file /builds/worker/workspace/build/src/ipc/chromium/src/base/shared_memory_posix.cc, line 250
```

**Are you currently working around this issue?**

I have tried to with what I explained just before, but it won't work due to the ACL attached to the volume and due to the fact that, as for now, ECS Fargate disallow using `/dev/shm` and `tmpfs`.

A previous issue was open [here](https://github.com/aws/amazon-ecs-agent/issues/2324). @fenxiong suggested to re-open the issue in this repository.
