### ISSUE TITLE
[EKS] [request]: Create a notification for new versions of the EKS Optimized AMI

### ISSUE THREAD

**Issue by jicowan** [aws/containers-roadmap#734]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
What do you want us to build?
Create an SNS topic for notifying customer when a new version of the EKS Optimized AMI is available.  

**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
What outcome are you trying to achieve, ultimately, and why is it hard/impossible to do right now? What is the impact of not having this problem solved? The more details you can provide, the better we'll be able to understand and solve the problem.
Today, you have to call an API to upgrade the worker nodes in a managed node group.  A notification would tell customer when a new version is available for upgrade. 

**Are you currently working around this issue?**
How are you currently solving this problem?
Customers can monitor the GitHub repository, e.g. https://help.github.com/en/github/receiving-notifications-about-activity-on-github/watching-and-unwatching-releases-for-a-repository. 

**Additional context**
Anything else we should know?

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

**Comment by tabern** [comment]
@jicowan do you imagine this is just a notification or also includes some sort of metadata about the status of the AMI (tests passing, etc...)?

**Comment by jicowan** [comment]
When the image has been published and is ready for consumption.  If the message includes metadata, it should include the AMI version/region, and SSM path.

**Comment by arun-krishnakumar** [comment]
+1

**Comment by philm** [comment]
ECS has had this functionality since 2017 - https://aws.amazon.com/about-aws/whats-new/2017/03/introducing-notifications-for-new-amazon-ecs-optimized-ami-releases/. Can that implementation be leveraged for this need?

**Comment by jayackri** [comment]
We are waiting for this feature to automate our AMI upgrade story. After the SNS feature has been launched by EKS, is there a way to get notified only after a new version has been released globally?

**Comment by ryanpflynn** [comment]
I have worked around this by having a CloudWatch Event rule invoke a lambda function that checks the eks-optimized ami SSM Parameters and save the last value per k8s version in a Dynamo DB table.

**Comment by bit-cloner** [comment]
Until AWS enables this feature natively . How about a mini Infrastructure as code package ( pulumi) that can create
1. SNS topic
2. Daily Lambda to check for new versions
3. Post to SNS if there is a new Version
If there is a enough interest I can work on this. Also would be nice to collaborate with someone

**Comment by cchostak** [comment]
For anyone interested. I made a sample Cloudformation template that can be deployed into the same region as the EKS cluster.

The template below has only two parameters required that are self explanatory:

`CLUSTER => The Cluster name to search for managed node groups. (All node groups there will be updated)`
`RATE => The rate that you want the update version call to be made.`

The method is idempotent and can be executed safely:

`1. If there are no AMI updates the node group will remain in the same version without disruption.`
`2. If there are updates, the flow will follow the update config specified and the nodes will be taken one at a time.`

The usage:

```sh
1. Navigate to Cloudformation Console.
2. Upload the template attached (template.yaml).
3. Change the Cluster name and Rate as needed.
4. Deploy it.
```

The YAML template:
```yaml
AWSTemplateFormatVersion: '2010-09-09'
Description: Lambda function to update Managed Node Groups for a given cluster based on a specific interval.
Parameters:

  CLUSTER:
    Type: String
    Default: efs
    Description: The Cluster name to search for Managed Node Groups

  REGION:
    Type: String
    Default: eu-central-1
    Description: The Cluster region

  RATE:
    Description: >
      The rate (frequency) that determines when CloudWatch Events runs the rule that
      triggers the Lambda function.
    Default: rate(10 minutes)
    AllowedValues:
      - rate(10 minutes)
      - rate(1 day)
      - rate(7 days)
      - rate(30 days)
    Type: String

Resources:

  LambdaSchedule:
    Type: "AWS::Events::Rule"
    Properties:
      Description: >
        A schedule for the Lambda function..
      ScheduleExpression: !Ref RATE
      State: ENABLED
      Targets:
        - Arn: !Sub ${UpdateFunction.Arn}
          Id: LambdaSchedule

  LambdaSchedulePermission:
    Type: "AWS::Lambda::Permission"
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName: !Sub ${UpdateFunction.Arn}
      Principal: 'events.amazonaws.com'
      SourceArn: !Sub ${LambdaSchedule.Arn}

  UpdateFunction:
    Type: AWS::Lambda::Function
    Properties:
      Runtime: python3.8
      Role: !GetAtt LambdaExecutionRole.Arn
      Handler: index.handler
      Environment:
        Variables:
          cluster: !Ref CLUSTER
          region: !Ref REGION
      Code:
        ZipFile: |
          from __future__ import print_function
          import os
          import boto3

          client = boto3.client('eks')

          def handler(event, context):
              cluster = os.getenv("cluster", None)
              region = os.getenv("region", None)

              if cluster and region:
                  message = "Env vars are there cluster: {} region: {}!".format(cluster, region)
                  # List Node Groups inside cluster
                  response = client.list_nodegroups(
                      clusterName=cluster,
                  )
                  try:
                      for nodegroup in response['nodegroups']:
                          print("Node Group => {}".format(nodegroup))
                          response = client.update_nodegroup_version(
                              clusterName=cluster,
                              nodegroupName=nodegroup,
                          )
                          message = "Update => {}".format(response)
                  except:
                      message = "Something went badly wrong, do you have Managed Node groups in this cluster?"
              else:
                  message = "No env vars passed"

              print(message)
              return message
      Description: The function that perform the API Update call

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      Policies:
      - PolicyName: root
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action: '*'
              Resource: '*'
```
