### ISSUE TITLE
[EKS] [request]: EKS CA should honor SAN x509 extension

### ISSUE THREAD

**Issue by mightyguava** [aws/containers-roadmap#750]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
Add support to the EKS CA to create certificates with SANs extensions

**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**

We would like to create mTLS certs for pods operating as part of a cluster that needs to communicate peer to peer. At the minimum, the pods need to be able to identify as the service's DNS, and the pod's DNS. This can't be done using the EKS CA right now because it ignores the SAN x509 extension. Even if the CSR contains SANs, the signed cert generated by the CA drops them.

**Are you currently working around this issue?**

There are a few non-ideal workarounds, see

https://github.com/cloudfoundry-incubator/cf-operator/commit/cbab593f3280ccbc76a84f3f6cf2a7c03f383f13
https://github.com/pingcap/tidb-operator/issues/1685

Both seem to require modifying the application to use an alternative TLS verification scheme.

**Additional context**
This issue was raised here as well https://github.com/awslabs/amazon-eks-ami/issues/341.

**Comment by davidnqd** [comment]
I just want to note that the "[Create a Certificate Signing Request object to send to the Kubernetes API](https://kubernetes.io/docs/tasks/tls/managing-tls-in-a-cluster/#create-a-certificate-signing-request-object-to-send-to-the-kubernetes-api)" example in the Kubernetes documentation does not work on EKS:

> Generate a CSR yaml blob and send it to the apiserver by running the following command:
```
cat <<EOF | kubectl apply -f -
apiVersion: certificates.k8s.io/v1beta1
kind: CertificateSigningRequest
metadata:
  name: my-svc.my-namespace
spec:
  request: $(cat server.csr | base64 | tr -d '\n')
  usages:
  - digital signature
  - key encipherment
  - server auth
EOF
```
