### ISSUE TITLE
[EKS] Add StorageClass st1, sc1 by default

### ISSUE THREAD

**Issue by runningman84** [aws/containers-roadmap#81]
**Tell us about your request**
Right now eks clusters only support gp2 storage class out of the box.

**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Providing storage classes for all supported aws storage solution sounds like a no brainer.

**Are you currently working around this issue?**
We apply these templates via kubectl apply
```
kind: StorageClass
apiVersion: storage.k8s.io/v1
provisioner: kubernetes.io/aws-ebs
metadata:
  name: st1
parameters:
  type: st1
reclaimPolicy: Delete
```
```
kind: StorageClass
apiVersion: storage.k8s.io/v1
provisioner: kubernetes.io/aws-ebs
metadata:
  name: sc1
parameters:
  type: sc1
reclaimPolicy: Delete
```

**Additional context**
We used to apply a similar template for gp2 but this seems to be included by default in recent eks deployments. Funny enough the docs still mention that you have to create a gp2 storage class:
https://docs.aws.amazon.com/eks/latest/userguide/storage-classes.html
