### ISSUE TITLE
[EKS] [request]: Add Prometheus annotations to default coredns podspec

### ISSUE THREAD

**Issue by otterley** [aws/containers-roadmap#821]
One issue I found with the default configuration of coredns in EKS is that the relevant Prometheus annotations are missing from the podspec. This is a relatively easy fix that will make it much easier for our users to see the metrics upon installing Prometheus into their clusters.

The patch follows:

```
apiVersion: extensions/v1beta1
kind: Deployment
spec:
  template:
    metadata:
      annotations:
        prometheus.io/port: "9153"
        prometheus.io/scrape: "true"
```
