### ISSUE TITLE
[EKS/Fargate] [request]: Schedule evenly pod replicas across AZs

### ISSUE THREAD

**Issue by lorenzomicheli** [aws/containers-roadmap#824]
**Tell us about your request**
At the time being, we have observed that there is no guarantee that EKS cluster on Fargate schedule pod replicas evenly across multiple Availability Zones.

**Which service(s) is this request for?**
Fargate, EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
We have a fargate profile with 1 namespace and the 2 private subnets. We have a deployment with 2 replicas and we would like that each replica is deployed on a different AZ. 
At the time being this behaviour is not guaranteed. 

We identified two test cases:
1) Scaling a deployment from 1 replica to 2 replicas: we observed that the 5 times out of 10, the replicas were deployed in the same AZ.

2) Starting from a new deployment configured with 2 replicas: we observed that 3 times out of 10, the replicas were deployed in the same AZ.

**Are you currently working around this issue?**
Currently we are not aware of any workaround.

**Comment by Gowiem** [comment]
@lorenzomicheli and anyone else following this - Has anyone tried using K8s 1.18's [`topologySpreadConstraints`](https://kubernetes.io/docs/concepts/workloads/pods/pod-topology-spread-constraints/) to deal with this problem? Or will that not work as the Fargate scheduler actually triggers the "node" provision? I'm assuming it does not, but wanted to check before I tried myself 😄

**Comment by lennartt** [comment]
I have the same question as @Gowiem. Unless I'm doing something wrong, the topologySpreadContraints does not seem to be a solution here. Has anyone tried this with success?

**Comment by clemensg** [comment]
Hi! We have a hard requirement of having at least one pod scheduled to each of 3 AZs in a specific region.
Am I right to assume that we have to use managed node groups because topologySpreadConstraints are not (yet?) supported with EKS+Fargate?

**Comment by r0mdau** [comment]
Scheduling evenly is not always pure, but I can recommend using `affinity.podAntiAffinity` as described here https://aws.github.io/aws-eks-best-practices/reliability/docs/application/#schedule-replicas-across-nodes

**Comment by wmosher** [comment]
> Scheduling evenly is not always pure, but I can recommend using `affinity.podAntiAffinity` as described here https://aws.github.io/aws-eks-best-practices/reliability/docs/application/#schedule-replicas-across-nodes

When `topologySpreadConstraints` didn't work as advertised I found this issue and tried last comment.  The `affinity.podAntiAffinity` solution also did not do the trick.  For example, out of 3 available AZs, two scheduled in `b` and two scheduled in `c`, and then scaling to a fifth it was scheduled in `b`.

I would love to hear if there is a plan to get one of these, or some other way to achieve the objective of them, working.

**Comment by foxlollato** [comment]
Hello everyone,
I am having the same issue and wondering about having differents fargate profiles (each one with specific AZ defined) should workout.
Does anyone have tried anything related?

**Comment by foxlollato** [comment]
> Hello everyone, I am having the same issue and wondering about having differents fargate profiles (each one with specific AZ defined) should workout, hence should have a namespace for each AZ as well, or better, create differents fargate profiles regarding same namespace but adding a specific label for the desired AZ. This should work, once You must define the subnets for each fargate profile. Does anyone have tried anything related?

```
Fagate-profile-A
    subnet_id: subnet-id-from-az-a
    podSelectors:
        namespace: my-namespace
        app: my-app
        zone: us-east-1a
    
Fagate-profile-A
    subnet_id: subnet-id-from-az-b
    podSelectors:
        namespace: my-namespace
        app: my-app
        zone: us-east-1b
```
        
Something like this.

**Comment by Youssef-Beltagy** [comment]
There are two current approaches. I recommend the second one. For both approaches, you will have to make a deployment for each AZ.

## Approach 1

1. Prepare subnet1 and subnet2 for the AZ1 and AZ2, respectively.
2. Prepare FP1 with subnet1 and an FP1 selector. 
3. Prepare FP2 with subnet2 and an FP2 selector. This selector must be unique and different from FP1's selector. **Don't use the same selector for FP1 and FP2.**
4. For the replica-set you want in FP1, launch it with the labels for FP1. Do the same for FP2.

Don't leave room for ambiguity on which fargate profile a pod should be mapped to.

## Approach 2 (recommended)

Create a fargate profile with subnets for both AZ1 and AZ2. You can specify which AZ a pod can be matched to in the pod spec. 

```
apiVersion: apps/v1
kind: Deployment
  replicas: 1
  template:
    spec:
      nodeSelector:
        topology.kubernetes.io/zone: us-east-1a
    containers:
        - name: fargate
          image: "nginx"
```

**Comment by marknelissen** [comment]
@Youssef-Beltagy although this solves the "physical" location of the pods, how do you do add stuff like routing, service, autoscaling, etc. on top of these actually separated deployments?

**Comment by visit1985** [comment]
Doesn’t #1125 solve this?

**Comment by WDaan** [comment]
I've found that the following config gives me somewhat the desired behavior:

```
      topologySpreadConstraints:
      - maxSkew: 1 # only 1 pod diff per az
        minDomains: 3 # use at least 3 AZ's
        topologyKey: 'topology.kubernetes.io/zone'
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
          ...
```

This way there are at least 3 zones being used, everything scaled above that is still somewhat random and not always perfectly balanced. `ScheduleAnyway` or `DoNotSchedule` doesn't really make a difference.

Any input?

**Comment by jennerm** [comment]
This does not seem to be working for us.  We have the following topologySpreadConstraints on our deployment:
```
      topologySpreadConstraints:
      - labelSelector:
          matchLabels:
            app.kubernetes.io/instance: karpenter
            app.kubernetes.io/name: karpenter
        maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: DoNotSchedule
```
But sometimes we see both fargate nodes in the same AZ:
```
name                                                   az           nodepool   instance-type   arch
fargate-ip-100-80-192-164.eu-west-1.compute.internal   eu-west-1a   <none>     <none>          amd64
fargate-ip-100-80-194-106.eu-west-1.compute.internal   eu-west-1a   <none>     <none>          amd64
```
I looked at https://github.com/aws/containers-roadmap/issues/1125 referenced above, but it only seems to talk about using nodeSelector or nodeAffinity rather than than topologySpreadConstraints.
