### ISSUE TITLE
The Name attribute of an AWS::ECS::Service resource returns the Cluster Name instead of the Service Name

### ISSUE THREAD

**Issue by talawahtech** [aws/containers-roadmap#86]
When using a CloudFormation template, if I try to get the name of an ECS service using `!GetAtt AppService.Name` it returns the name of the Cluster instead of the name of the Service.

I assume this has to do with the fact the ECS ARN format has [recently changed](https://aws.amazon.com/ecs/faqs/#Transition_to_new_ARN_and_ID_format) and now includes the cluster name (and I opted into the change).

Old: `arn:aws:ecs:region:account-id:service/service-name`
New: `arn:aws:ecs:region:account-id:service/cluster-name/service-name`

I was deliberately trying to use the `Service.Name` attribute instead of splitting the arn on `/` to avoid future breakage if the format changes, but it looks like that is actually the approach currently being taken to derive `Service.Name` which results in the cluster-name being returned instead.

**Comment by jcputney** [comment]
Running into this issue as well. Glad it's not just me, because this was driving me up a wall.

**Comment by roguemolecule** [comment]
I'm seeing the same issue

**Comment by andy-swanson** [comment]
Yes I have been trying to figure this out for hours as I assumed I incorrectly specified the ResourceId for a ScalableTarget. After trying to solve via several different iterations I finally started to look for "know issues" and here I am. This makes leaving service naming dynamic impossible if you want to use service autoscaling...

**Comment by NotMrSteve** [comment]
You can work around this issue by using the `Fn::Select` and `Fn::Split` available in Cloudformation. The following YAML snippet shows how to do this:
```
  Service:
    Type: "AWS::ECS::Service"
    Properties: ...

  ServiceAutoscaleTarget:
    Type: "AWS::ApplicationAutoScaling::ScalableTarget"
    Properties:
      ResourceId: !Select
        - "5"
        - !Split
          - ":"
          - !Ref Service
```
