### ISSUE TITLE
[service] :Issues in giving access to an IAM user in cross-account via aws-auth configmap

### ISSUE THREAD

**Issue by hayderimran7** [aws/containers-roadmap#883]
**Tell us about your request**
we have a EKS cluster in separate account, and want to give full access to this kubernetes environment to a user in different account. so first we created cross-account IAM role for that user with policy permissions only to EKS service.  

and then we added that user to aws-auth configmap as:
```
  mapUsers: |

    - groups:

      - system:masters

      userarn: arn:aws:iam::<ACCOUNT_ID>:user/user@company.ccom

      username: user@company.com
```
however the user is still seeing `error: You must be logged in to the server (Unauthorized)` when it tries to run `kubectl get <RESOURCE>` 

is there anything else missing here? how does one give EKS access to IAM user in different account (cross-account)

**Which service(s) is this request for?**
EKS version 1.15

**Comment by aviau** [comment]
Give them access to a role.

**Comment by hayderimran7** [comment]
ok i got it fixed. literally had to add  the  cross-account EKS role and cross-account iam user   AND source account role + source account iam user..
just copy paste and change account IDs 
```
    - "groups":
      - "system:masters"
      - "system:nodes"
      "rolearn": "arn:aws:iam::<SOURCE_ACCOUNT_ID>:role/CrossAccountEKS"
    - "groups":
      - "system:masters"
      - "system:nodes"
      "rolearn": "arn:aws:iam::<CROSS_ACCOUNT_ID>:role/CrossAccountEKS"
  mapUsers: |
    - groups:
      - system:masters
      userarn: arn:aws:iam::<SOURCE_ACCOUNT_ID>:user/user@company.com
      username: user@company.com
    - groups:
      - system:masters
      userarn: arn:aws:iam::<CROSS_ACCOUNT_ID>:user/user@company.com
      username: user@company.com
```
