### ISSUE TITLE
[EKS] [request] Coredns manifest has reference to extensions/v1beta1

### ISSUE THREAD

**Issue by kaykay88** [aws/containers-roadmap#905]
As per the AWS guide to upgrade EKS clusters [here](https://docs.aws.amazon.com/eks/latest/userguide/update-cluster.html):

> DaemonSet, **Deployment**, StatefulSet, and ReplicaSet resources will no longer be served from extensions/v1beta1, apps/v1beta1, or apps/v1beta2 in v1.16. Migrate to the apps/v1 API, available since v1.9. Existing persisted data can be retrieved through the apps/v1 API. For example, to convert a Deployment that currently uses apps/v1beta1, enter the following command.

And in the guide to upgrade coredns [here](https://docs.aws.amazon.com/eks/latest/userguide/coredns.html) the manifest file provided is `https://amazon-eks.s3.us-west-2.amazonaws.com/cloudformation/2020-05-08/dns.yaml`.This file has reference  to **extensions/v1beta1** under Deployment resource:

```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: coredns
  namespace: kube-system
  labels:
    k8s-app: kube-dns
.
.

```
So upgrading cluster to 1.16 using this manifest would break coredns deployment. 

In my opinion the manifest should be updated as per the requisites of kubernetes version 1.16.
